hmrc/assets-frontend

assets/javascripts/modules/SSO_links.js, package.json
=> Replace SSO portal form with get request

.gitignore, README.md, assets/Gruntfile.js, assets/package-build.json, server.sh
- Convert root package.json to template at assets/package-build.json
- Pass --release=VERSION to build tasks to process template
=> No more version bumping!

assets/scss/modules/_navigation.scss
```
<nav class="tabs-nav" role="navigation">
<span class="tabs-nav__tab--active">Tab 1 (Active)</span>
<a class="tabs-nav__tab" href="#">Tab 1</a>
</nav>
```
=> Update tabbed nav styles to use more semantic markup

assets/scss/base/_buttons.scss, assets/scss/base/_form.scss, assets/scss/base/_typography.scss, assets/scss/modules/_header.scss
Reverts hmrc/assets-frontend#43
=> Revert "Misc rules and adjustments as per commit messages"

assets/javascripts/modules/registerBlockInputFields.js
Fix for adding and removing class on radio button list
=> Fix on CATO-1517 for Radio buttons

assets/scss/_application-base.scss, assets/scss/base/_buttons.scss, assets/scss/base/_typography.scss, assets/scss/pages/_payments.scss
* Added SASS file to target payment pages.
* Adjusted button paddings and line height to match style guide.
* Added specific styles for payment pages based on Guy's requirements.
=> PAYM-490: Styles added for Payments pages.

assets/scss/modules/_notifications.scss
=> [notifications] add alert class for new style error/success messages

assets/scss/pages/_payments.scss
Aligned pay now hint text with Worldpay icon.
=> [PAYM-482] Aligned pay now hint text with Worldpay icon.

assets/scss/base/_layouts.scss
Added styles to ensure side bar is not displayed in mobile view. 
The sections contained in this side bar are now also duplicated in the main content.
=> [YTA-687] YTA Dashboard - Added styles to ensure side bar is not displayed in mobile.

assets/scss/base/_lists.scss
Added "action-list__grouped" class for items which don't have a top border, e.g. payment items.
=> [YTA-706] Added action-list__grouped class.

assets/scss/base/_lists.scss
Moved action-list__grouped class back into action-list nesting
=> [YTA-706] Moved action-list__grouped class back into action-list nesting

assets/scss/modules/_navigation.scss, assets/scss/modules/_template-service-info.scss
=> YTA-753 - Updated breadcrumb styles

assets/scss/base/_buttons.scss, assets/scss/base/_lists.scss, assets/scss/base/_table.scss, assets/scss/base/_typography.scss, assets/scss/modules/_navigation.scss, assets/scss/modules/_notifications.scss, assets/scss/modules/_unknown.scss
- smaller buttons
- thick bottom borders on default tables
- abstract .panel-indent from details
- underlined headings
- back link tweaks
- failure alert
=> Align styles with prototypes

assets/scss/base/_form.scss
Styling fixes for mobile view survey page (form elements)
=> YTA-688 - Styling fixes for mobile view survey page (form elements)

assets/scss/pages/_messages.scss
=> [SA-584] Added penalty section styles for messages.

assets/scss/pages/_business-tax-home.scss
Override default icon position and file url.
=> YTA-770: Add external link icons to YTA homepage help links. 

assets/scss/pages/_messages.scss
Replaced nth-of-child(1) on table header with class to target marker column for messages table.
=> [SA-647] Replaced nth-of-child(1) on table header with class.

assets/javascripts/modules/details.polyfill.js
Added condition to prevent existing aria roles being overwritten on summary tags
=> [SA-663] Added condition to prevent existing aria roles being overwritten

assets/javascripts/modules/enhancedTables.js, assets/javascripts/modules/sticky-header.js, assets/package.json, assets/scss/_application-base.scss, assets/scss/modules/_datatables.scss, assets/scss/pages/_client-list.scss
- Rely on inherited left value
- Use class instead of setting css with js.
- jQuerify for cross-browser ease
- Fix client-list table widths
=> [AOSS-231] Convert sticky-header to custom module

assets/scss/_application-base.scss, assets/scss/base/_table.scss, assets/scss/modules/_client-list.scss
- Move client-list from pages to modules and add nowrap for phone numbers
- Consistant font sizes for paras in table cells.
=> Table cell paras and telephone numbers

assets/scss/base/_colours.scss
Updated the error colour to match https://github.com/alphagov/govuk_frontend_toolkit/pull/171
This is related to https://github.com/hmrc/assets-frontend/pull/105
=> DDCNFF-808 Changed error colour to match new accessability guidelines

assets/package.json
Adding JSON support for older browsers
=> TXM-331 add JSON support

assets/javascripts/modules/exitSurveyValidation.js
removes the unneccesary wrapper 'return function() { ', which stops it being initialised in application.js
=> [YTA-862] Fix client-side validation on exit survey form.

assets/scss/pages/_payments.scss
Moved epaye inline styles into here, added hover for inner expanded list items as per prototype
=> PAYM-633 - Moved epaye inline styles into here, added hover for inner lists

assets/javascripts/modules/attorneyBanner.js
Added check to prevent code from running if bannerId is undefined.
=> [PAYM-633] Added check to prevent execution if bannerId is undefined

assets/scss/pages/_payments.scss
Reverts hmrc/assets-frontend#127
=> Revert "[PAYM-694] Added padding for time text container and alert icon"

assets/govuk_elements/public/sass/elements/forms/_form-date-of-birth.scss, assets/gulpfile.js/config.js, assets/gulpfile.js/tasks/build.js, assets/gulpfile.js/tasks/default.js, assets/gulpfile.js/tasks/modernizr.js, assets/package.json
=> Missing modernizr

assets/scss/modules/_epaye-statements.scss
AOSS-389+429 L&P statements updates from UX review
* bullets on specified charges list
* wrapping on period title cells
* padding on period title cells where no data returned
* bottom border on table on annual statement view
* delegation-banner css
* annual statements view year navigation+ message  floats and padding
=> Aoss 389+429 l+p statement

assets/scss/modules/_epaye-statements.scss
* add background #f8f8f8 to monthly statements (including message)
* cursor to default + remove ARIA outline on empty monthly fields
=> AOSS 443 L&P minor design issues

assets/scss/base/_form.scss
Updated radio button styles to apply appropriate border and background colours
=> [PAYM-797] Updated radio button styles

assets/scss/pages/_business-tax-home.scss, server.sh
[yta-918] Mobile breakpoint modifications. Also apply link list style to 'other services' section.
[yta-918] Adjust styles per UX feedback.
=> [yta-918] adjustments to menu links on YTA homepage.

assets/javascripts/modules/enhancedTables.js
To fix disappearing checkbox during form post's on the client and verification list.
https://jira.tools.tax.service.gov.uk/browse/AOSS-262
=> Aoss 262 cbox disaappers

assets/javascripts/application.js, assets/javascripts/modules/ajaxCallbacks.js, assets/test/specs/ajaxCallbacks.spec.js, assets/test/specs/ajaxFormSubmit.spec.js, assets/test/specs/fixtures/ajax-form-client-access-request.html, assets/test/specs/fixtures/client-access-request-responses.html
Move callbacks and helpers to separate file, refactoring ajax tests + adding callback helper tests:
* fix button selector in resetForm() helper function
* move callbacks object from application.js to ./modules/ajaxCallbacks.js for testing
* remove Jasmine Async logic and setTimeout's
* use jasmine-jquery to preload fixtures and restructure tests accordingly
* add responses fixture html & helper function for loading html fragments
* add ajaxCallback helper tests
=> Buttons remain disabled after successful or failing AJAX behaviour form post

assets/javascripts/modules/preventDoubleSubmit.js
Added check to prevent disabling buttons if "ignore-double-submit" data attribute exists on the button
=> [SA-855] Added check to prevent disabling buttons if data attribute exists

assets/scss/_application-base.scss, assets/scss/modules/_panel.scss, assets/scss/modules/_unknown.scss, assets/scss/pages/_email-notifications.scss
Updated indent class to override generic panel-indent margin as more spacing is needed between these elements
=> [SA-855] Updated indent class to override generic panel-indent margin

assets/javascripts/modules/ajaxCallbacks.js, assets/javascripts/modules/ajaxFormSubmit.js
AOSS-730 - Request for existing clients access issue
* fix selector scope in ajaxFormSubmit
AOSS-731 - Request for access redirects login page on session timeout
* abandon access request when user session timed out (triggers error callback and response.readyState === 0) and redirect user to sign-in (with 'continue' parameter to return to page - won't work locally because of port number)
AOSS-680 - Client list page error message styling
* add inline error before button when full page error returned
=> Aoss 680 730 731 client requests

assets/javascripts/modules/enhancedTables.js
Updated tableSubmit() method to add missing checkboxes to form submit
=> [AOSS-557] Updated tableSubmit() method to add missing checkboxes

assets/scss/modules/_dashboard.scss
https://jira.tools.tax.service.gov.uk/browse/AOSS-786
* override styles Agent-FE Dashboard Page
* for public beta
=> AOSS-786 - Agent Dashboard Page

assets/scss/modules/_dashboard.scss, assets/scss/pages/_client-list.scss
[AOSS-810] Home page link on Client list page
https://jira.tools.tax.service.gov.uk/browse/AOSS-810
* add .agent-breadcrumb override rule to #global-breadcrumb for client-list pages "home" link (remove bottom border and add padding)
=> Aoss 810 client list breadcrumbs

assets/javascripts/modules/SSO_links.js
* open sso link in new browser tab/page if "target" attribute is set on <a/> element
=> AOSS-846-Open-new-tab-SSOLinks

assets/scss/pages/_client-list.scss
* client list grid sidebar css update
=> AOSS-832-clientlist-sidebar

assets/scss/modules/_epaye-statements.scss
[AOSS-878](https://jira.tools.tax.service.gov.uk/browse/AOSS-878) Statements link and showing links on additional statements page
[AOSS-891](https://jira.tools.tax.service.gov.uk/browse/AOSS-891) PAYE Statement Overview Sidebar links CSS update
[AOSS-892](https://jira.tools.tax.service.gov.uk/browse/AOSS-892) PAYE Statement Detail Sidebar links CSS update
=> Statements_FrontEnd Account Summary (Overview) and Statement page presentation updates

assets/scss/_application-base.scss, assets/scss/modules/_breadcrumb.scss
Our own small version of breadcrumbs - not reliant on govuk_elements
=> Simple breadcrumbs

assets/scss/modules/_dashboard.scss
[AOSS-904](https://jira.tools.tax.service.gov.uk/browse/AOSS-904) Dashboard CSS updates
Also updating top level class to remove product specific prefix:
.agents-services--dashboard >> .services-dashboard
=> AOSS 904 - Agent Dashboard page sidebar item spacing

assets/javascripts/modules/ajaxCallbacks.js, assets/javascripts/modules/ajaxFormSubmit.js
[AOSS-917](https://jira.tools.tax.service.gov.uk/browse/AOSS-917) 409 errors when requesting access to view L&P data in client-list
* ajaxSubmit
- Adds 'beforeSend' pre post callback function
- Adds DOM element argument to pass the origin event target
* ajaxCallbacks
- Adds parameter for DOM element to all clientAccessResponse.callbacks functions
- Adds 'beforeSend' callback function to clientAccessResponse.callbacks - disabling origin event target element
=> AOSS-917 409 errors when requesting access to view L&P data in client-list

assets/scss/base/_buttons.scss
- addition of pseudo-link class to make a button look behave like a link
=> Make a button look like a link

assets/javascripts/application.js, assets/javascripts/modules/accordion.js, assets/scss/_application-base.scss, assets/scss/base/_icons.scss, assets/scss/modules/_accordion.scss, assets/test/config/karma.conf.js, assets/test/specs/accordion.spec.js, assets/test/specs/fixtures/accordion-fixtures.html
Accordion Module
Usage:
<div class="accordion" data-accordion>
<div class="accordion__row">     
<i class="arrow arrow--right" data-accordion-arrow></i>
<a href="#" data-accordion-button>Accordion Title</a>  
<div data-accordion-reveal>
<p>Optionally reveal content that is not part of the body on expand</p>
</div>
</div>
<div class="accordion__body hidden" data-accordion-body>                        
<p>Accordion Body</p>
</div>
</div>
NOTES: 
- All data attribute hooks are mandatory
- These classes are mandatory: accordion, accordion__body, hidden
- All other classes are optional
- The arrow is optional
- data-accordion-expanded can be placed on the container to expand by default
Example of use in API Developer Hub:
=> [API-571] Accordion module + tests

assets/javascripts/application.js, assets/javascripts/modules/accordion.js, assets/javascripts/modules/tabs.js, assets/scss/modules/_accordion.scss, assets/test/specs/fixtures/tabs-fixtures.html, assets/test/specs/tabs.spec.js
Tabs module
Usage:
<div data-tabs>
<ul>
<li>
<a href="#" data-tab-link="1">Tab Link 1</a>
</li>
<li>
<span data-tab-link="2">Tab Link 2</span>
</li>
<li>
<a href="#" data-tab-link="3">Tab Link 3</a>
</li>
</ul>
<ul>
<li data-tab-content="1">
<p>Tab Content 1</p>
</li>
<li data-tab-content="2">
<p>Tab Content 2</p>
</li>
<li data-tab-content="3">
<p>Tab Content 3</p>
</li>
</ul>
</div>
Example usage in API Developer Hub:
=> [API-571] Simple styles-agnostic tabs module + tests

assets/scss/base/_layouts.scss
* add new module with thick blue top border.
=> [YTA-1199] Add sidebar subsection module style.

assets/javascripts/application.js, assets/javascripts/modules/youtubePlayer.js, assets/scss/_application-base.scss, assets/scss/modules/_youtube-player.scss
* Replace existing hard-coded iframe on page with module, using Youtube iFrame API.
https://developers.google.com/youtube/iframe_api_reference.
* Multiple videos may be rendered on a page.
* data-attribute params for video ID and optional data attribute for custom Google Analytics event fired when video is started.
* Add style for responsive sizing of player container element.
=> [YTA-1012] Youtube video player module

assets/scss/base/_errors.scss
Added fields-aligned class to ensure error fields lined up with others.
=> [API-540] Added fields-aligned class

assets/scss/base/_helpers.scss, assets/scss/modules/_code.scss
Moved word wrap fix from specific class to generic word-wrap class
=> [API-686] Moved word wrap fix from specific class to generic word-wrap

assets/scss/base/_form.scss
- update to styles
- bit of tidy up
- brought styles over from govv uk elements
=> GG-359: Update to Form styles for 2fa

assets/javascripts/application.js, assets/javascripts/validation/customValidations.js, assets/javascripts/validation/form.js
Place attributes on form inputs and add the class .js-form to your form.
JavaScript error messages added in your markup using the .error-notification class
Server side errors handled by using `@if(registrationForm("phoneNumber").hasErrors){ error}`
```
<fieldset class="form-field-group@if(registrationForm("phoneNumber").hasErrors){ error}">
<legend class="visuallyhidden">@Messages("otpfe.enter_mobile.page.header")</legend>
<label class="form-element-bold" for="phoneNumber">
Label text
<span class="error-notification" role="tooltip" data-journey="search-page:error:phoneNumber">
Error Message
</span>
<span class="form-hint">
Form Hint
</span>
<input type="text"
name="phoneNumber"
value="@registrationForm("phoneNumber").value"
id="phoneNumber"
class="form-control"
minlength="10" …
```
=> GG-359: Generic validation

assets/javascripts/application.js, assets/javascripts/modules/autoComplete.js, assets/javascripts/modules/masker.js, assets/javascripts/modules/toggle.js, assets/javascripts/validation/form.js
- Toggle updated to flush errors on form
- Masker added
- Generic Form validation improved
=> Gg 407 tweaks

assets/scss/base/_buttons.scss
Set margin top on button link in mobile, removed borders from button link
=> [API-679] Set margin top on button link in mobile, removed borders

assets/scss/modules/_panel.scss
Move margin out into modifier so it doesnt clash with YTA
@benaveryee
=> Move gutter to modifier

assets/javascripts/modules/SSO_links.js
- Remove comments (these are no longer relevant)
- Fix use of indexOf as this isn't supported in IE8
@rpowis comments removed, I won't add an issue for this as this is all moving to Scala
=> IE8 SSO fix

assets/scss/modules/_panel.scss
=> tidy up after discussion

assets/scss/base/_icons.scss
=> GG-398: exclamation icon

assets/scss/modules/_tabular-data.scss, assets/scss/pages/_business-tax-home.scss
Modify tabular data styles on small screens.
Tidy up unused styles.
=> [YTA-1230] Modify tabular data styles on small screens

assets/javascripts/modules/masker.js, assets/javascripts/utils/caretPosition.js
=> CARROT: change name to an easily recognisable thing

assets/javascripts/application.js, assets/javascripts/modules/autoCompleteFactory.js, assets/javascripts/modules/control.js, assets/javascripts/modules/masker.js, assets/javascripts/modules/toggle.js, assets/javascripts/modules/visibility.js, assets/javascripts/utils/caretPosition.js, assets/javascripts/validation/form.js
=> return objects not functions

assets/javascripts/modules/charCounter.js, assets/scss/base/_colours.scss, assets/scss/base/_form.scss, assets/scss/modules/_navigation.scss
Changes:
* Added modifier for "form-fields" class to provide more space.
* Add margin top on first element of tab contents.
* Added global border and background colour on all inputs and text areas, as agreed by designers.
=> [API-698] Input styles, tab content spacing, form field spacing.

assets/javascripts/application.js, assets/javascripts/modules/addRemove.js, assets/scss/_application-base.scss, assets/scss/modules/_add-remove.scss, assets/scss/modules/_navigation.scss, assets/test/specs/addRemove.spec.js, assets/test/specs/fixtures/addRemove-fixture.html
Module for handling a list of items that can be added or removed, with a max items. If the max items is reached, the add button is removed. If an item is then deleted, the add button is restored.
```
<div id="addRemove1"
class="add-remove"
data-add-remove
data-add-remove-max="5"
data-attr-name="redirectUris[$]">
<script type="text/template" data-item-template>
<li class="add-remove--item" data-add-remove-item data-removable>
<input type="text" value="" data-add-remove-unique/>
</li>
</script>
<script type="text/template" data-remove-btn-template>
<a href="#" class="add-remove__remove-btn" data-remove-btn>Delete</a>
</script>
<script type="text/template" data-add-btn-template>
<a href="#" data-add-btn>Add another redirect URI</a>
</script>
<ul data-add-remove-list>
<li data-add-remove-item …
```
=> [API-689] Add/Remove module + tests

assets/javascripts/modules/youtubePlayer.js
Additional data attribute data-video-id to allow a link to change the played video.
=> [YTA-1317] Can select new video in Youtube player module.

assets/javascripts/application.js, assets/javascripts/modules/mask.js
Simple module to show/hide a secret.
This is JavaScript functionality only @stingrayfunk is doing styles in separate work
Tests to be done (problems with Karma runner in intellij have meant I haven't got these done today)
=> API-756: mask work

assets/javascripts/modules/mask.js, assets/test/specs/fixtures/mask-fixture.html, assets/test/specs/mask.spec.js
- added tests and fixture for mask work, 
- updated mask example documentation
=> Tests for mask work

assets/test/specs/ajaxFormSubmit.spec.js, assets/test/specs/fixtures/ajax-form-client-access-request.html
* update to fix spec causing test fail in previous merge to master 
* also update  fixture to match missing client page form
=> [AOSS-1082] Test fix for AjaxFormSubmit Spec

assets/scss/_application-base.scss, assets/scss/base/_helpers.scss, assets/scss/modules/_accordion.scss, assets/scss/modules/_navigation.scss
I've also made some adjustments to the accordion styles, replacing floats with display table cell.
=> API-691 - Accordion module refactored

assets/scss/_application-base.scss, assets/scss/modules/_toggle-button.scss
Styles for toggle button, currently operating solely as links.
=> API-691 - Toggle button module styles

assets/scss/base/_buttons.scss
[AOSS-1058](https://jira.tools.tax.service.gov.uk/browse/AOSS-1058) 
* improve accessibility:
* move verify/delete buttons to each client table row (renamed as confirm & remove)
* remove checkboxes
**CSS changes**
* update button styles for table:
=> [AOSS-1058] Client list redesign

assets/scss/modules/_notifications.scss, assets/scss/pages/_business-tax-home.scss
* Add new important alert style
* Migrate reusable alert styles in business-tax specific scss into notifications.scss
* Migrate measurements in both files from px to ems where appropriate.
=> [YTA-1439] Add alert for live seminar link.

assets/scss/base/_buttons.scss
=> AOSS-1083 Buttons variant .button--table color update

assets/scss/modules/_notifications.scss
Notification's "highlight message" variant updates:
- indented variant
- icon positioned in top left variant 
- dark background, light text variant
=> AOSS-1083 Notification variant updates

assets/javascripts/application.js, assets/javascripts/modules/passwordReveal.js, assets/test/specs/fixtures/password-reveal-fixture.html, assets/test/specs/passwordReveal.spec.js
A simple password reveal for showing the password.
- Password reveal
- Associated tests
=> Gg 492 password reveal

assets/javascripts/modules/ajaxFormSubmit.js
AOSS-1135 Ajax Form Submit handler
- update selectors to support data-attributes on form elements (as per module header comments)
=> [AOSS-1135] Ajax Form Submit handler

assets/scss/modules/_panel.scss
Added a new variation of panel-indent to highlight changes.
=> TAI-1139 added a varient of panel-indent

assets/scss/modules/_breadcrumb.scss
Component Library Comments for the breadcrumbs
=> component-library-documentation: breadcrumbs work

component-lib.json, gulpfile.js/config.js, gulpfile.js/tasks/comp-lib.js
This is a bit of work to add assets-frontend `JavaScript` file into the component library
=> Component library JavaScript

component-lib.json
Add the ability to include custom helpers from the component library template
- `isSection` [helper](https://github.com/hmrc/component-library-template/blob/master/helpers/isSection.js)
- `countryCodes` [partial](https://github.com/hmrc/component-library-template/blob/master/helpers/countryCodes.js)
=> Custom handlebars helpers - component library

README.md
Information on how to update the component-librarydependency in assets-frontend
=> how to update the component-library

assets/javascripts/modules/autoComplete.js
A few tweaks on aria roles and accessibility on the autoComplete
- added `role="option"` to `li` elements in suggestions
- added `role="listbox"` to `ul` suggestions container
- added `aria-selected="true"` on `li` elements in suggestions when selected
=> Aria Roles AutoComplete

assets/scss/_application-base.scss, assets/scss/components/_character-counter.scss
added character counter to textArea section
=> Component-library: character counter

assets/scss/_application-base.scss, assets/scss/components/_toggle-button.scss
comments for the toggle button
=> Component library - toggle button

assets/scss/base/form/_errors.scss
Added component library comments to the form errors file
=> Component library - Form Errors

assets/scss/base/_icons.scss
Added comments for the component library for Icons
=> Component Library - Icons

assets/scss/_application-base.scss, assets/scss/components/_template-sidebar.scss
Template sidebar component library comments, moved to components folder
=> Component Library - Template sidebar

assets/scss/_mixins.scss, assets/scss/base/_layouts.scss, assets/scss/modules/_hero.scss
Refactored existing hero component as it wasn't self-contained and relied on other classes.
=> Hero component

assets/scss/_application-base.scss, assets/scss/components/_template-page-header.scss
page header comp lib comments and moved to components folder
=> Component Library - Page Header

assets/scss/components/_page-header.scss, assets/scss/components/_template-page-header.scss
Switch the deprecated flag from page header to template page header
=> Component Library: switch the deprecated flag - page header

README.md
Updated ReadMe to include link to deployed component library.
=> Updated ReadeMe to refer to deployed component library

assets/scss/_application-base.scss, assets/scss/components/_tabular-data.scss
* Move into component library.
* Add modifier classes to place two rows closer together when fields are related, e.g. name and address.
Before
After
=> Yta 1762-b: Amend tabular data and add to component lib

assets/javascripts/modules/mask.js, assets/test/specs/fixtures/mask-fixture.html, assets/test/specs/mask.spec.js
Added ability to place accessible text after the "Show" or "Hide" so that the link is contextual in itself for screen readers.
=> Updated mask module to be accessible

assets/scss/base/_details.scss, assets/scss/base/_table.scss, assets/scss/modules/_datatables.scss
- added comp lib documentation for tables
- moved details table work into details
- move datatable work into datatables
=> Component library tables documentation

assets/javascripts/modules/ajaxCallbacks.js
The following changes are releated to PR https://github.com/hmrc/assets-frontend/pull/559
=> Updated class names related to PR 559

assets/scss/base/_colours.scss, assets/scss/components/_attorney-banner.scss
@feedmypixel - as discussed, this PR is to allow the colour of attorney banner to be changed
https://github.com/hmrc/play-ui/pull/51
=> ATED-1669: added css to change banner colour - as discussed

.stylelintrc
A few additions to the stylelint rules without having to refactor any of our `.scss` files
http://stylelint.io/user-guide/rules/
=> Additions to style lint rules

assets/scss/base/form/_form.scss
=> component-library: added form validation example

assets/scss/base/form/_form.scss
Add more information around validation for the component library description
=> component-library - form validation description

assets/javascripts/modules/ajaxCallbacks.js, assets/javascripts/modules/ajaxFormSubmit.js
Progressive enhanced API hub to add/remove collaborators using Ajax
Added 2 API specific callbacks:
`apiCollaboratorResponse` is called when new collaborator is added
`apiCollaboratorRemoveResponse` is called collaborator is removed
also updated `serializeForAjax` to support radio input types
=> Progressive enhanced API hub to add/remove collaborators using Ajax

assets/scss/base/_lists.scss
Myself and @timsb have been documenting the `lists.scss` file.
Comments more than welcome to myself and @timsb
=> Component library documentation for lists

assets/javascripts/modules/SSO_links.js, assets/javascripts/modules/sso.js
Allow forms with a GET method to do sso via the form button and the data-sso attribute. Mimics the anchor sso functionality
=> form-action-client-sso

gulpfile.js/config.js, gulpfile.js/tasks/default.js, gulpfile.js/tasks/images.js, gulpfile.js/tasks/svg.js, package.json
Added gulp-svgmin in build process
Excluded svg files from `images` build process
=> Added gulp-svgmin in build process

assets/javascripts/modules/toggle.js
Toggle radio button functionality currently only works for single target.  Updated it to support multiple target based on selection.
=> add toggle support for multiple radio buttons

styleguide.md
Final content tweaks associated with https://github.com/hmrc/assets-frontend/pull/667
=> [FE-222] Updates to component lib homepage

assets/scss/components/_organisation-logo.scss
=> Update organisation logo text in component library

assets/scss/components/_app-info.scss
=> APIS-851 Developer status CSS.

assets/javascripts/modules/autoComplete.js
Adds missing js-suggestions class to suggestions list.
=> Updated example code in autoComplete

assets/scss/base/_icons.scss
This is used to highlight actioned content to the user.
Example usage:
=> tick-icon: Added a styled tick icon.

assets/javascripts/modules/ajaxCallbacks.js, assets/test/specs/ajaxCallbacks.spec.js
The application title is hard coded to "API Developer Hub". We need to change the title of the application depending on which environment the application is deployed.
The application title will be dynamically set in the page and the javascript will use this value for the message.
=> Apis 1216 emailmessage

assets/test/specs/enhancedTables.spec.js, gulpfile.js/tasks/default.js, gulpfile.js/tasks/test.js
The Karma tests do not fail the travis build if they fail.
Make the travis build fail when the Karma tests do
=> Js tests not failing in travis

CHANGELOG.md
Some of the changes made as pull requests since the last release were missing from the new change log file.
Add the missing pull requests to `CHANGELOG.md`
=> Update CHANGELOG with missing PR changes

CHANGELOG.md
Hotfix branch for releasing from.
=> Update CHANGELOG for 2.242.2 release

CHANGELOG.md
The change log isn't up to date
Update the change log
=> Update changelog with release info

CHANGELOG.md, README.md
The README.md needs updating to reflect the changes
As the app requires a new version of Node we need to mention this in the README.md
Updated README.md
=> Updated the README.md as the node version has been bumped up

CHANGELOG.md
2.248.1 was released from this branch so we just need to merge it back into master
=> Update change log for 2.248.1 release

CHANGELOG.md
=> Update change log for 2.251.0

CHANGELOG.md
=> Update change log for 2.251.1 release

CHANGELOG.md
Releasing a hotfix has to happen _before_ the branch has been merged to master so I've had to add this commit to release from.
Now it's been released it can be merged.
=> Update change log for releasing 2.251.1

CHANGELOG.md
Created change log section for version 2.252.0
=> Update change log for release 2.252.0

CHANGELOG.md, gulpfile.js/tasks/changelog.js, gulpfile.js/tasks/test.js, gulpfile.js/tests/changelog.test.js, gulpfile.js/tests/parseDocumentation.test.js, gulpfile.js/tests/renderPagesFromTemplate.test.js
Travis CI fails on CHANGELOG check using commit hash based diff.
Modify the verification step to compare the file against master instead.
=> Sdt 666 change log check fails on travis

CHANGELOG.md, assets/components/header/README.md
Content review of HMRC header documentation
=> Updated header documentation

assets/components/account-menu/README.md
Notice that this pattern is not yet ready to use in production code.
=> Account menu README.md update

CHANGELOG.md, gulpfile.js/tasks/changelog.js, gulpfile.js/tests/changelog.test.js
Travis build fails during changelog verification
Use revision numbers to check if the build runs against master with detached head
=> Sdt 687 fix git diff comparison

assets/patterns/README.md
There was a dashed line in the readme file
This PR removes the dashed line
=> Removed dashed line from the readme file

CHANGELOG.md, design-system.md
The homepage of the design system did include information about patterns
This PR adds a paragraph to the design system homepage (copied from the GOV.UK design system) that explains what a pattern is
=> Updated the Design System home page with content relating to patterns

.gitignore, CHANGELOG.md, assets/components/old-component-library/README.md, assets/styles/README.md, assets/styles/colour/README.md, assets/styles/component-library/README.md, assets/styles/icons-and-images/README.md, assets/styles/layout/README.md, assets/styles/typography/README.md, design-system.md, gulpfile.js/config.js
Styles are not available on the DS.
Add links to the HomePage and introduce a menu, both pointing the old Component Library.
=> Sdt 707 styles

CHANGELOG.md
=> Update change log for 2.540.0

CHANGELOG.md
=> Update changelog for release 3.0.1

CHANGELOG.md, assets/components/account-header/account-header-example.html, assets/components/header/header--signed-in.html, assets/components/header/header.html
404 for fallback header logo
Update the image path
=> fix image reference in header and account header components

CHANGELOG.md
=> Updating Changelog for release 3.0.2

CHANGELOG.md, gulpfile.js/util/pattern-library/lib/parseDocumentation.js, gulpfile.js/util/pattern-library/macros/research.html, gulpfile.js/util/pattern-library/macros/wip.html
Changes the content and arrangement of the work in progress banner. Adds a similar banner for more research needed.
=> Changed WIP macro and added research macro

CHANGELOG.md
Release notes for 3.1.0 and 4.1.0
=> Update change log for 3.1.0 and 4.1.0

CHANGELOG.md, assets/scss/base/_buttons.scss, package-lock.json
Fixes #908. Example markup in the component library does not represent how the latest classes from govuk-elements should be used. And not all the classes are documented in govuk-elements.
Given we have the examples documented in the component library we should provide examples which represent how the classes should be used.
Removed the base class `button` from all non standard `button--variation` classes as these variation classes are not overrides rather they are fully styled buttons.
=> Sdt 768 update button markup examples to better reflect how govuk-elements classes should be used

CHANGELOG.md
Change log update for hotfix releases.
=> Release 3.2.1 and 4.2.1

CHANGELOG.md
=> Update changelog for releasing 3.2.2 and 4.2.2

CHANGELOG.md, assets/components/account-header/README.md, assets/components/account-header/account-header-example.html, assets/components/account-menu/account-menu.html, assets/components/account-menu/account-menu.test-mobile.js, assets/components/account-menu/account-menu.test.js, gulpfile.js/tasks/images.js, gulpfile.js/tasks/style.js, gulpfile.js/tasks/svg.js, gulpfile.js/tasks/test.js
The markup used in the Account Menu (and by extension the Account Header) example isn't up to date with [that being used in production](https://github.com/hmrc/govuk-template/blob/master/resources/templates/mustache/production/govuk-template.mustache.html).
Update the markup and tests to use that of production.
=> Sdt 789 update account header example

CHANGELOG.md, assets/patterns/ask-users-for-their-consent/README.md, assets/patterns/ask-users-for-their-consent/ask-users-for-their-consent-checkbox.html, assets/patterns/ask-users-for-their-consent/ask-users-for-their-consent-checkboxes.html, assets/patterns/ask-users-for-their-consent/ask-users-for-their-consent-yes-no-question.html
Pattern to ask usrs for consent in a way that meets GDPR and DPA requirements with a yes-no question, single checkbox or multiple checkboxes.
=> Ask users for their consent

CHANGELOG.md
Updated CHANGELOG.md for release, moved line for the last change into the correct segment.
=> Updage changelog for releases 3.3.1 and 4.3.1

CHANGELOG.md, assets/patterns/add-to-a-list/README.md
Deleted nonsense characters from documentation
=> Updated add to a list documentation

CHANGELOG.md, assets/components/README.md, assets/components/account-header/README.md, assets/components/notification-badge/README.md, assets/components/open-links-in-a-new-window-or-tab/README.md, assets/components/page-heading/README.md, assets/components/page-title/README.md, assets/patterns/add-to-a-list/README.md, assets/patterns/ask-users-for-their-consent/README.md, assets/patterns/header/README.md, assets/patterns/help-users-when-we-time-them-out-of-a-service/README.md, assets/patterns/page-not-found/README.md
Small changes to documentation to make the content more active, shorter and use more plain English.
=> Small edits to documentation

CHANGELOG.md, assets/patterns/page-not-found/README.md
Delete a line from previous version of documentation.
=> Updated page not found documentation

CHANGELOG.md, assets/patterns/ask-users-for-their-consent/README.md
Received feedback to make it clearer when the pattern should not be used.
=> Updated ask users for their consent documentation

assets/components/page-heading/README.md
As per @torydunn-hmrc 's suggestion, changed "secondary heading" to "supraheading"
=> changed name of secondary heading to supraheading

CHANGELOG.md, assets/error_pages/400.html
Platform Nginx proxies expect a default 400 error page which we don't have, to get the latest other pages accepted they would like us to provide a 400 page too
Created a default 400 page with content based on the existing 500 error page
=> SDT-891 Draft of a default 400 page

CHANGELOG.md
Updated CHANGELOG.md for release 3.5.0 and 4.5.0
=> Update CHANGELOG.md for release 3.5.0 and 4.5.0

CHANGELOG.md, assets/patterns/service-unavailable/README.md, assets/patterns/service-unavailable/service-unavailable-after.cy.html, assets/patterns/service-unavailable/service-unavailable-after.html, assets/patterns/service-unavailable/service-unavailable-before.cy.html, assets/patterns/service-unavailable/service-unavailable-before.html, assets/patterns/service-unavailable/service-unavailable-general.cy.html, assets/patterns/service-unavailable/service-unavailable-general.html, assets/patterns/service-unavailable/service-unavailable-link.cy.html, assets/patterns/service-unavailable/service-unavailable-link.html, assets/patterns/service-unavailable/service-unavailable-no-replacement.cy.html, assets/patterns/service-unavailable/service-unavailable-no-replacement.html, assets/patterns/service-unavailable/service-unavailable-replacement.cy.html, assets/patterns/service-unavailable/service-unavailable-replacement.html, assets/patterns/service-unavailable/service-unavailable.cy.html, assets/patterns/service-unavailable/service-unavailable.html
Added new titles and updated Welsh language versions.
=> Updated service unavailable pages

CHANGELOG.md, assets/patterns/service-unavailable/service-unavailable-before.html
=> Small tweak to service unavailable example

CHANGELOG.md, assets/components/accounts-office-reference/README.md, assets/components/accounts-office-reference/accounts-office-reference-heading.html, assets/components/accounts-office-reference/accounts-office-reference-label-error.html, assets/components/accounts-office-reference/accounts-office-reference-label.html, assets/components/employer-paye-reference/README.md, assets/components/employer-paye-reference/employer-paye-reference-heading.html, assets/components/employer-paye-reference/employer-paye-reference-label-error.html, assets/components/employer-paye-reference/employer-paye-reference-label.html, assets/components/unique-taxpayer-reference/README.md, assets/components/unique-taxpayer-reference/unique-taxpayer-reference-corporation-tax-heading.html, assets/components/unique-taxpayer-reference/unique-taxpayer-reference-corporation-tax-label-error.html, assets/components/unique-taxpayer-reference/unique-taxpayer-reference-self-assessment-heading.html, assets/components/unique-taxpayer-reference/unique-taxpayer-reference-self-assessment-label.html, assets/components/vat-registration-number/README.md, assets/components/vat-registration-number/vat-registration-number-heading.html, assets/components/vat-registration-number/vat-registration-number-label-error.html, assets/components/vat-registration-number/vat-registration-number-label.html
Added:
- Accounts Office reference
- Employer PAYE reference
- VAT registration number
- Unique Taxpayer Reference
No new styles or JavaScript needed.
=> Added references info

CHANGELOG.md, assets/patterns/cannot-confirm-identity/cannot-confirm-identity-avoid.cy.html, assets/patterns/cannot-confirm-identity/cannot-confirm-identity-avoid.html, assets/patterns/cannot-confirm-identity/cannot-confirm-identity.cy.html, assets/patterns/cannot-confirm-identity/cannot-confirm-identity.html, assets/patterns/confirmed-identity/README.md, assets/patterns/confirmed-identity/confirmed-identity.html, assets/patterns/could-not-confirm-identity/README.md, assets/patterns/could-not-confirm-identity/could-not-confirm-identity-avoid.cy.html, assets/patterns/could-not-confirm-identity/could-not-confirm-identity-avoid.html, assets/patterns/could-not-confirm-identity/could-not-confirm-identity-specific.cy.html, assets/patterns/could-not-confirm-identity/could-not-confirm-identity-specific.html, assets/patterns/could-not-confirm-identity/could-not-confirm-identity.cy.html, assets/patterns/could-not-confirm-identity/could-not-confirm-identity.html
Updated documentation, examples and Welsh.
Renamed cannot confirm pattern to could not confirm.
=> Updated identity patterns

CHANGELOG.md, gulpfile.js/tests/fixtures/pattern-library/design-pattern-library-template.html, gulpfile.js/tests/renderPagesFromTemplate.test.js, gulpfile.js/util/design-system/lib/renderPagesFromTemplate.js
Update the way the mobile navigation is being built to include subnavigation items which can be expanded on the mobile navigation.
=> SDT-959 mobile navigation

CHANGELOG.md, design-system.md, package-lock.json
=> Sdt 979 add deprecation banner to documentation

CHANGELOG.md, assets/components/vat-registration-number/README.md, assets/patterns/page-not-found/page-not-found.html, assets/patterns/service-unavailable/service-unavailable-after.html, assets/patterns/service-unavailable/service-unavailable-general.html, assets/patterns/service-unavailable/service-unavailable-link.html, assets/patterns/service-unavailable/service-unavailable-replacement.html, assets/patterns/service-unavailable/service-unavailable.html, assets/patterns/there-is-a-problem-with-the-service/there-is-a-problem-with-the-service-no-contact.html, assets/patterns/there-is-a-problem-with-the-service/there-is-a-problem-with-the-service.html
=> Updated VAT registration number

CHANGELOG.md, package-lock.json, package.json
Some of our dependencies bring in compromised dependencies. This change brings in newer dependencies without the vulnerabilities.
=> Bump dependencies

CHANGELOG.md, repository.yaml
=> DDCNLS-1439-Updating the exemptions in repository.yaml file.

CHANGELOG.md, assets/application.js, package-lock.json, package.json
=> PLATUI-764 uplift jquery and PLATUI-800 uplift browser-sync

assets/javascripts/modules/attorneyBanner.js, gulpfile.js/tests/utils/test-repo.js
[assets-frontend Jenkins build](https://build.tax.service.gov.uk/job/PlatUI/job/Libraries/job/assets-frontend/) failing due to the following error in `git-describe.test`
`fatal: ambiguous argument 'main': unknown revision or path not in the working tree.`
update git helper to explicitly set the default branch to `main`
=> PLATUI-1707 set default branch name explicitly in git test helper; fix broken link in attorneyBanner docstring

repository.yaml
=> NOJIRA: Removed unused exemptions flagged by LDS

.nsprc
=> NOJIRA: Fixed npm vulnerabilities

.nsprc
=> NOJIRA: Updated excluded npm vulnerabilites

README.md
=> PLATUI-2158: Updated the README with how to run the microsite locally
