- assets/scss/modules/_unknown.scss
Changed the full-width css class to be more general, so we can use it for something besides the now-discarded article tag. With @siliconcat.
> [PAYM-379] 

- assets/scss/base/_lists.scss
- assets/scss/base/_typography.scss
Added class 'badge' to target any badges (red blocks "New", "Unread", "Overdue" etc) that appear in action lists, e.g. Tax Summary link.
> [SA-583] Added left and right margins for flags

- assets/scss/base/_typography.scss
- assets/scss/modules/_unknown.scss
To align styles with [GDS](http://govuk-elements.herokuapp.com/#typography-hidden-text) by underlining *only* the summary text, nest a `span.summary` inside the `<summary>` element.
i.e.
```
<summary>
<span class="summary">Authorisation levels explained</span>
</summary>
```
> Move details styles to _typography and add underline to summary

- assets/scss/modules/_organisation-logo.scss
> use correct icon sizes instead of relying on background-size to scale up hmrc icon.

- assets/javascripts/modules/details.polyfill.js
The suppression of keypress events for spaces was preventing the entry of any spaces on any form fields on the screens that use summary/details widgets (in IE, Chrome & Safari).  Allow the event if the target is anything else other than the document body.
> CATO-2328 - fix for space characters being suppressed

- assets/javascripts/application.js
- assets/javascripts/modules/ajaxFormSubmit.js
- assets/scss/base/_buttons.scss
- assets/test/specs/ajaxFormSubmit.spec.js
- assets/test/specs/fixtures/ajax-form-client-access-request.html
Adds AJAX form POST handler, using form/button element attributes to override the HTML form submit event:
* POSTs data via AJAX to avoid page reloads;
* Configure data callback functions for success or error in name-spaced object under properties for 'page > module';
* USAGE:  
Place the attribute `data-ajax-submit="true"` on either a form tag or a button
that has:
- a `formaction` attribute for non-javascript enabled form post (full page reload)
- a `data-container` attribute with a selector for the element which contains 'scoped' form values to be posted;
- a `data-callback-name` attribute with name-spaced object property name with contains 'success' and 'error' property functions;
- a `data-callback-args` attribute containing comma separated list of argument parameters to pass to …
> AOSS-329 Ajax behaviour for PAYE Client List page

- assets/javascripts/application.js
- assets/javascripts/modules/ajaxFormSubmit.js
- assets/test/specs/ajaxFormSubmit.spec.js
- assets/test/specs/fixtures/ajax-form-client-access-request.html
* update "ajaxFormSubmit.js":
- add 'always' event hook to call callback function (if configured)
- add 'data-formacton' attribute for use in ajaxed submit, allowing non-javascript to  use  formaction - simplifying controller by reducing forking in Result actions
* update clientList callbacks "application.js":
- add 'always' callback to be run when success/error has executed:
+ enable all buttons in client list page
+ update all emails to submitted value
- refactor success, error & always callback logic into  clientList.helpers object, for re-use:
+ i.e. the 'error' callback uses the same dom update function as 'success', to deliver validation errors via ajax
> AOSS-447 Missing client link refactoring

- assets/javascripts/modules/ajaxCallbacks.js
- assets/scss/pages/_client-list.scss
- assets/test/specs/ajaxCallbacks.spec.js
* update client-list page CSS with error message styling
* update ajaxCallbacks.helpers.insertResponseHtml:
+ use $.parseHtml (error partial view may have more than 1 validation error on missing client form)
+ handle error positioning (between label and invalid field)
> AOSS-680 - Client list page error message styling

- assets/scss/base/_helpers.scss
- assets/scss/pages/_business-tax-home.scss
[YTA-1061] Separate style for YTA manage account display elements after a summary-details element, due to needing absolute positioning.
> [YTA-1061] Styles for new Manage Account page on YTA.

- assets/scss/base/_form.scss
Having the float information 
```
float: left;
clear: right;
```
on `fieldset legend` was causing clipping of the `legend` when in mobile view.
I had a sanity check with @benaveryee on YTA and this also fixed the same problem for him.
@stingrayfunk as cleanup potentially [this](https://github.com/hmrc/assets-frontend/blob/master/assets/scss/pages/_payments.scss#L22-L24) over ride could be removed now?
> [PE-1518] Remove float styles that are causing clipping in "mobile" view

- assets/scss/_application-base.scss
- assets/scss/base/_grid.scss
A hmrc owned implementation of grid layout to give us full height columns.
> Api 564 full height grid

- assets/govuk_frontend_toolkit/stylesheets/_css3.scss
- assets/govuk_frontend_toolkit/stylesheets/_grid_layout.scss
- assets/govuk_frontend_toolkit/stylesheets/_measurements.scss
- assets/scss/base/_grid.scss
- assets/scss/modules/_breadcrumb.scss
- assets/scss/modules/_side-navigation.scss
- Tweaks for regressed styles
- Update some govuk_frontend_toolkit mixins/helpers
- Update the gird implementation to use styles taken from govuk_frontend_toolkit
- Use preferred BEM layout for styles (non nested)
I have added the:
- **mixin grid-column-table**
- **placeholder selector” %grid-row-table**  
These are implementations from govuk_frontend_toolkit that use display:table rather than floats.
@rpowis this is first cut on this process.
> Api 525 tweaks on regressed styles

- assets/javascripts/modules/SSO_links.js
- assets/javascripts/modules/sso.js
Some work to support failure cases from a failed GET in the SSO encryption process.
- After a grep of the codebase tightened up the selector for SSO functionality so its not on all anchors
- Inject failure response into page
- Take event.preventDefault() back into listener rather than sending back from SSO_Links
- Added TODO to split this functionality out
- Added general Comment
> GG-292: improve error functionality, refactor, add TODO and comment

- assets/scss/_application-base.scss
- assets/scss/base/_details-summary.scss
- assets/scss/modules/_epaye-statements.scss
* BEM-ify class names
* Incorporates fix for [AOSS-910](https://jira.tools.tax.service.gov.uk/browse/AOSS-910) Firefox browser: Multiple Expand icons for statements on the L&P page (statements_frontend)
- details section(s) in Statements-FE views required vertical alignment of arrow due to multi-line summary block ([screen-cast of statement views nested details / summary sections](https://drive.google.com/a/hmrc.gov.uk/file/d/0By6oX4FdFRoMeEFWenlybHFtcUU/view?usp=sharing))
This introduced a bug caused where epaye-statements.css hid native details marker and applied 'arrow'  character to `<span class="summary"/>` element in Statements-FE views,
where poly-fill injected `<i class="arrow" />`:
Fix introduces `@mixin multi-line-summary-block`, which extends the `<summary/>` arrow positioning …
> Statemens-FE - epaye-statements.css BEM updates + statements-fe bug fix

- assets/scss/base/_grid.scss
Removed media queries from grid layout helper classes to prevent media query nesting (which is not cross-browser safe).
> [API-674] Removed media queries from grid layout helper classes

- assets/scss/base/_form.scss
I have been seeing issues on firefox with the select inheriting `font-size: 100%`
> normalize select font size

- assets/scss/modules/_code.scss
Added break all to inline snippets, ensuring URLs and such non-breaking strings wrap correctly.
> [API-686] Added break all to inline snippets

- assets/javascripts/application.js
- assets/javascripts/modules/tabs.js
- assets/scss/modules/_navigation.scss
- assets/scss/modules/_tabular-data.scss
- assets/test/specs/fixtures/tabs-fixtures-auto-open.html
- assets/test/specs/tabs.spec.js
* Allow selected tab to be opened on page load from URL hash.
* Behaviour configurable by adding class to containing element.
* If enabled but no matching URL hash, first tab is opened.
* If not enabled, clicking tabs does not add hash to URL.
* active and inactive tab classes are added to match styles defined in _navigation.scss.
> [YTA-1193] Extend tab functionality and add classes for styling.

- assets/javascripts/application.js
- assets/javascripts/modules/visibility.js
Visibility Module to change aria hidden state dependant on JavaScript capability
Show or hide elements by changing respective aria-hidden attribute
The visual styles can be controlled by using the `.visible-javascript-on` and `.hidden-javascript-on` CSS selectors
Used for displaying markup and altering aria details dependant on browser JavaScript ability
> GG-359: Visibility Module

- assets/javascripts/application.js
- assets/javascripts/modules/toggle.js
- assets/scss/_application-base.scss
- assets/scss/_mixins.scss
- assets/scss/base/_form.scss
- assets/scss/base/_helpers.scss
- assets/scss/modules/_toggle.scss
Helper to enable elements to toggle other elements on the page specified by data attribute
Attach event to parent as delegate, open close dependant on triggers id.
```
<fieldset class="form-field-group visible-javascript-on js-aria-show js-toggle"
id="uk-number"
data-target="uk-phone-number-toggle-target"
data-trigger="js-toggle-trigger"
data-open="uk-phone-number-toggle-open"
data-close="uk-phone-number-toggle-close"
aria-hidden="true">
<label class="block-label block-label--inline" for="uk-phone-number-toggle-close">Yes
<input type="radio"
id="uk-phone-number-toggle-close"
class="js-toggle-trigger js-control"
value="yes"
name="uk-number"
required
data-control-target="countryCode"
data-control-value="44"/>
</label>
<label class="block-label block-label--inline" …
```
> Gg 359: toggle module

- assets/javascripts/application.js
- assets/javascripts/modules/control.js
A module to enable an element to control the value of another specified form input on the page.
Helper to enable elements to control the value of an input else where on the page specified by a data attribute
```
<label class="block-label block-label--inline" for="uk-phone-number-toggle-close">Yes
<input type="radio"
id="uk-phone-number-toggle-close"
class="js-toggle-trigger js-control"
value="yes"
name="uk-number"
required
data-control-target="countryCode"
data-control-value="44"/>
</label>
```
In the example you can see (in the console) the yes button sets an input to `44`,
The no button sets an input to `0`
> GG-359: Control Module 

- assets/scss/base/_errors.scss
> [API-639] Updated error fields in mobile to not have left red border

- assets/javascripts/validation/form.js
I need to purge errors from the internal JQuery validation error List array when flushing errors as well as purging the pages global summary of errors otherwise the errors will continue to be highlighted by JQuery Validation when showing or hiding inputs.
> I need to have a refactor as to how this works as JQuery Validation offers a lot and I suspect I can hook into it in some better ways once I know its capabilities
> GG-407: Purge errorList in JQuery Validation

- assets/scss/_shame.scss
- assets/scss/modules/_phase-beta.scss
Added styles to position BETA banner within nav
Moved BETA colour into correct selector, removed from shame.scss
> [API-634] Added styles to position BETA banner within nav

- assets/scss/base/_layouts.scss
- assets/scss/modules/_template-sidebar.scss
* BEM classes rather than nested styles using elements.
* old default behaviour was to hide sidebar at mobile breakpoint.
* new behaviour drops content below main article at mobile breakpoint, with optional style to hide.
* move all sidebar behaviour and style into _template-sidebar.scss
This might be a visually breaking change. Some markup conversion is needed to use the new styles. 
Apply the following classes to the markup:
- .sidebar class to the aside element.
- if the sidebar should be hidden at the mobile breakpoint, also apply .sidebar--hidden-sm to the aside.
- .sidebar__list to a ul 
- .sidebar__list-item to an li
- .sidebar__heading to any heading elements
- sidebar__list-item--lined-sm to li elements where a style with top and bottom borders should apply at the mobile …
> [YTA-1250] Convert sidebar to BEM, visible by default on small screens.

- assets/javascripts/modules/masker.js
- assets/javascripts/utils/caret.js
A bug has been raised where the user could not amend a number when masking was applied.
- Change the way masking is fundamentally done
- `data-masker-rule` now sends in what is accepted rather than what is not
- Added cross browser utils for caret position
> GG 448 | BUG - cannot amend number

- assets/govuk_elements/public/sass/elements/_forms.scss
- assets/scss/base/_links.scss
- assets/scss/base/_lists.scss
Added `.link-list` component class to support links in a list format
```html
<div class="link-list">
<a class="link-list__item"> ... </a>
<a class="link-list__item"> ... </a>
</div>
```
> GG-453: Link list component

- assets/javascripts/application.js
- assets/javascripts/modules/charCounter.js
- assets/scss/_application-base.scss
- assets/scss/modules/_char-counter.scss
- assets/test/specs/charCounter.spec.js
- assets/test/specs/fixtures/charCounter-fixtures.html
```html
<div class="char-counter" data-char-counter>
<textarea data-char-field maxLength="250"></textarea>
</div>
```
* Chrome counts new lines as two characters, while other browser count them as one. In non-Chrome browsers, sometimes it will say 0 characters remaining but let you type one more.
* In the scenario where one character is remaining and the user breaks the middle of some text onto a new line, the browser allows this but registers it as two characters giving a count of -1, so I've accounted for this showing a count of 0.
> [API-430] Character counter module + tests

- assets/javascripts/modules/autoComplete.js
- assets/javascripts/modules/autoCompleteFactory.js
Display the countryCode in the autocomplete (JavaScript working) and the dropdown (JavaScript broken) in the following format: (+355)
This work enables the use of a custom display template which is sent in on creation of the autoComplete.
- added ability to have a template for the suggestion display, 
- send in cutom display template for countries autoComplete
> GG-459: Custom suggestion display Template

- assets/scss/modules/_breadcrumb.scss
- slim version of breadcrumb nav, 
- tidy up pixel values being used
> GG-476: Slim modifier for breadcrumb nav

- assets/javascripts/modules/preventDoubleSubmit.js
- assets/javascripts/validation/form.js
The form.js was controlling the submit disabled value, on being made aware of other code we have to take care of this this has now been removed from the form.js work.
Removed conditional from preventDoubleSubmit as this code does not take into account the following scenario:
- fill out a form, 
- that form errors clientSide
- they fix the errors 
- the submit button gets re-enabled because of fixed errors
- they submit again
Due to the conditional wrapped around the disable code [preventDoubleSubmit](https://github.com/hmrc/assets-frontend/blob/master/assets/javascripts/modules/preventDoubleSubmit.js#L5) the submit button is not then re-disabled by this code, which means a user can “pump” the button! 
====================================
- Remove submit disable work from form.js 
- Remove …
> GG-483: Remove submit disable work from form.js

- assets/javascripts/application.js
- assets/javascripts/modules/tabs.js
- assets/test/specs/tabs.spec.js
Fixed issue where default tab is not selected correctly. This was due to the :first selector always targeting anchors when it should be element agnostic to consider spans.
* Removed init to keep things simpler (less code/boilerplate) and be consistent with other modules.
* Some jQuery selectors were global, so I scoped them within their $tabs instance.
* Clean up of logic in initial tabs setup. The "selectActiveTabWithJs" property doesn't need to be checked here as a fallback to the first tab is already written in the "findActiveTabFromHash" method (renamed to findActiveTab).
* Updated tests accordingly.
> [API-689] Bug fix and minor refactoring

- assets/scss/modules/_accordion.scss
* Converted pixels to use em() function
* Fine-tuned position of expand/collapse arrow
* Fixed the following padding issue in mobile:
The accordion__body__right container has a left padding of 0 in tablet/desktop as this sits as a right column and doesn't need it. In mobile, this container sits full width as a row. Therefore, left padding is necessary to align the content with the accordion button above it, to indent it.
> API-691 - Converted pixels to em(), fixed padding bug in mobile

- assets/scss/pages/_payments.scss
* page templates in Payments project had inline styles in a number of places due to no FE devs being available at the time.
* removed all inline styles from payments pages, using existing assets-frontend styles where available.
* added 2 style classes to payments-specific scss file.
> [PAYM-854] Remove inline styles from Payments pages.

- assets/scss/modules/_toggle-button.scss
Fixed issue where buttons were not evenly padded across breakpoints.
> API-691 - Removed core-16 mixin call, added line height

- assets/scss/pages/_client-list.scss
[AOSS-1082](https://jira.tools.tax.service.gov.uk/browse/AOSS-1058) 
* additional CSS update for this JIRA:
*  error selectors in _client-list.scss
> [AOSS-1082] Update _client-list error selector and dataTable column widths

- assets/javascripts/application.js
- assets/javascripts/modules/toggle.js
- assets/javascripts/validation/form.js
- assets/scss/_application-base.scss
- assets/scss/_shame.scss
- assets/scss/base/_helpers.scss
- assets/scss/base/form/_errors.scss
- assets/test/specs/fixtures/form-fixture.html
- assets/test/specs/form.spec.js
Refactor of the form work to include the capability of adding different messages for different rules.
- Add messages via `data-msg-<rule_name>`
- remove flushErrors dependency from `toggle.js`
- tidy up styles a bit
- add deprecated notice to styles
- tests
> Form refactor

- assets/javascripts/modules/enhancedTables.js
[AOSS-1058](https://jira.tools.tax.service.gov.uk/browse/AOSS-1058)
**JS change(s):**
* Bug fix *(blocking an AOSS pull request to be released once merged)*:
* make sticky-header functionality optional based on existance of element with selector ".controlpanel.stick"
* error breaks js call-stack if page uses dataTable
> [AOSS-1058] Client list redesign

- assets/javascripts/modules/tabs.js
- assets/scss/_application-base.scss
- assets/scss/modules/_navigation.scss
- assets/scss/modules/_tabs.scss
- assets/test/specs/fixtures/tabs-fixtures-auto-open.html
- assets/test/specs/fixtures/tabs-fixtures.html
I've updated the Tabs JS module to ensure tabs are fully accessible via keyboard and screen readers. 
I've also moved the tabs SASS from navigation.scss into its own module, tabs.scss.
The tabs markup has been updated as shown below. The JS switches the states of the aria-selected attribute on the tab links, and the aria-hidden attribute on the tab panels.
```html
<div data-tabs>
<ul role="tablist">
<li id="tab1" data-tab-link="1" role="tab" aria-selected="true" aria-controls="tabContent1" tabindex="0">
<span class="tabs-nav__tab tabs-nav__tab--active">Tab Link 1</span>
</li>
<li id="tab2" data-tab-link="2" role="tab" aria-selected="false" aria-controls="tabContent2" tabindex="0">
<a href="#" class="tabs-nav__tab">Tab Link 2</a>
</li>
<li id="tab3" data-tab-link="3" role="tab" …
```
> API-916 - Refactored tabs for accessibility + updated tests

- assets/scss/pages/_business-tax-home.scss
* Remove unneeded style for YTA specific scss file, which was causing the tab text to display too far to the left.
> [YTA-1427] Update tabs markup.

- assets/scss/base/_buttons.scss
Ensured buttons that look like links have focus outlines for visual keyboard accessibility
> API-719 - Minor button accessibility update

- assets/javascripts/validation/form.js
- assets/test/specs/fixtures/form-fixture.html
- added information about obtaining the fragments from play-ui, pending [PR #32](https://github.com/hmrc/play-ui/pull/32)
- made getting the associated input name easier
- removed `data-journey` work this is for page load events. To fire events on JavaScript errors this can be done using `data-journey-click` https://github.com/alphagov/stageprompt/#user-click-events
> Form Refactor: tweaks to the form refactor work

- assets/javascripts/modules/tabs.js
- assets/scss/base/_colours.scss
- assets/scss/modules/_tabs.scss
There are situations where the tabs may want to be used with minimal styling. For example, like this:
> API-916 - Added support for style-agnostic tabs

- assets/govuk_frontend_toolkit/stylesheets/_grid_layout.scss
- assets/scss/base/_grid.scss
Removed 100% width from grid-column-table mixin as it was overriding the width for non-media query browsers such as IE8.
> [API-684] Removed hard-coded 100% width from grid-column-table mixin

- assets/scss/base/form/_errors.scss
So it turns out that there is some markup that relies on the `.error` class, this is to cover that.
> GG-569: some markup relies on the error class

- assets/scss/modules/_phase-beta.scss
There are cases where the BETA banner should not have its default bottom grey border. This PR adds a modifier class to remove borders from the banner. Here's what I made earlier:
> [API-913] Added no-border modifier class to beta banner

- assets/javascripts/validation/customValidations.js
Add the ability to send in a flag for pattern validation via a data attribute
You can send in a flag for your regex via the `data-pattern-flags` on the input that has a `pattern` attribute
```html
<input type="password"
name="password"
id="password"
class="form-control--block input--medium"
aria-required="true"
required
pattern="^((?!password1).){8,12}$"
data-pattern-flags="i"
data-msg-pattern="Your password is not strong enough. Make sure it follows the rules above."
data-msg-required="Create your password"/>
```
> Flag for pattern validation

- assets/scss/base/_helpers.scss
A fixed width modifier was necessary to truncate text that sits within a width sensitive container, e.g. the header nav links. I called the modifier "fixed-small" as this could be the smaller of a variety of sizes. However, I can change this to just "fixed" if needs be? Providing a pixel width was done on purpose as the goal here isn't to provide a width relative to the font size, but rather a fixed pixel width.
> [API-758] Added fixed width modifier on truncate helper

- assets/javascripts/modules/formHintHelper.js
- assets/test/specs/fixtures/form-hint-helper-fixture.html
- assets/test/specs/formHintHelper.spec.js
The form hint helper module needs password confirmation functionality.
A hint label can name two input fields by ID.
If both are non-empty and have the same content, the hint will show the form-hint-list-item--valid class.
If both are empty, the hint will stay invalid.
> GG-492: Add matching two inputs form hint helper module.

- assets/javascripts/modules/accordion.js
- assets/test/specs/accordion.spec.js
- assets/test/specs/fixtures/accordion-fixtures.html
* On expand of an accordion, the URL hash is updated with the accordion's ID, if the accordion is configured to do so with the `data-accordion-set-hash` attribute.
* On page load, if the URL hash matches an accordion's ID, that accordion will be expanded.
* Improved jQuery selector usage in jasmine tests.
* Added a new suite of tests to cover this new functionality.
```
<div id="accordion1" class="accordion" data-accordion data-accordion-expanded data-accordion-set-hash>
<div class="accordion__row">     
<i class="arrow arrow--right" data-accordion-arrow></i>
<a href="#" data-accordion-button>Accordion Title</a>  
<div data-accordion-reveal>
<p>Optionally reveal content on expand that is not part of the body</p>
</div>
</div>
<div class="accordion__body hidden" data-accordion-body> …
```
> Updates to accordion module + tests

- assets/scss/base/_form.scss
* block label sets inputs such as radio buttons to be vertically centred.
* this adds a class to align such inputs to the top of the field, for example where the button should align with a title, with explanatory text below.
> GG-597: Add class to top align block-label input

- assets/javascripts/modules/formHintHelper.js
- assets/test/specs/fixtures/form-hint-helper-fixture.html
- assets/test/specs/formHintHelper.spec.js
After discussion with UX and a discussion about Client Side validation it has been decided that this work is taken care of in the validation layer.
The comparison of two inputs is outside the scope of this helper and is something that the validation offers for free. 
Although this could be done in this helper it feels like it is adding specifics to a generic module. Comparing two inputs feels more like a validation concern.
This work is a straight revert of the password comparison work.
FYI @benaveryee
> GG-626: Revert changes form hint helper

- assets/javascripts/modules/ajaxCallbacks.js
- assets/javascripts/modules/ajaxFormSubmit.js
- assets/test/specs/ajaxCallbacks.spec.js
- assets/test/specs/ajaxFormSubmit.spec.js
- assets/test/specs/fixtures/ajax-form-client-access-request.html
[AOSS-1135] Ajax submit and callback updates
- ajaxFormSubmit.js
- replace .attr('data-...') references to .data('...')
- add 'data-target-success' add 'data-target-error' attributes
-  selector of elements found within the element specified in data-container and are used by the relative  callbacks
- add reference to [ajaxCallbacks.helpers.]base object, defined in ajaxCallbacks.js
ajaxCallbacks.js
- add "dataTableSubmitResponse" callback
- rename clientAccessResponse callback to 'emailFormResponse'
- update success callback to reset form values to empty on elements which aren't "email" type (not just explicit for  name=payeref)
- refactor clientAccessResponse callback to use [ajaxCallbacks.helpers.]base objects for common code
- update .helpers:
- general:
- change .error class references …
> [AOSS-1135] Ajax submit and callback updates

- assets/scss/base/_table.scss
Added a variant for child of table element with a blue border.
> TAI-1139 added table--heavy-header

- assets/scss/base/form/_hint.scss
Reverted to using px for this svg and image as we were seeing problems with the size.
> Tick Icon Fix

- assets/javascripts/validation/form.js
- assets/test/specs/fixtures/form-fixture.html
- assets/test/specs/form.spec.js
For the front end validation due to having a summary added to the page we suffer from an undesirable movement when users invoke an error on the form (keyup, blur, submit), this is magnified on mobile. 
Working with UX to find a solution,
We have considered:
- taking the summary out of document flow (absolute, fixed)
- removing the summary (needed for Accessibility)
- making the front end validation work only on submit (I feel this removes the value front end validation gives you)
- hiding/removing the summary for JavaScript (gets tricky with Server side errors)
- locking the scroll position or compensating for an element added at the top of the page (gets tricky)
After trying many different options we have decided on:
- Don't show error summary when inline errors are invoked
- Show error …
> GG-627: Summary validation causing a jump when an inline error is shown

- assets/scss/modules/_tabular-data.scss
* reduce vertical padding on tabular-data__tab-content class, to make contents look more compact, as per updated prototype designs for YTA.
* convert all units except borders from px to em function.
> YTA-1588: adjust spacing in tabular data

- assets/scss/base/_lists.scss
Our `lists.scss` module contains an element selector `ul` which sets `list-style-type:none`.
If one wraps a `nav` tag around a `ul`, styles from `govuk-template.scss` override the `list-style-type`, causing list items to have be bullet pointed, as below:
I've updated our list module, adding a `nav ul` to the existing `ul` selector to prevent this happening, giving the follow:
Like many things we do with the SASS in its current state, the above is a symptom of a deeper problem. Technically, this problem is caused by govuk elements overriding our styles. This CSS is in the todo list to be removed.
> Preventing our list module styles being overridden by govuk elements

- assets/javascripts/modules/accordion.js
* Added toggle of `aria-expanded` attribute on accordion parent element upon expand/collapse.
* Added toggle of `aria-hidden` class on accordion body upon expand/collapse.
* Added `aria-controls` to accordion button linking it to accordion body.
* Added `role="button"` to accordion button.
* Updated usage docs.
> Accordion module - Updates for Accessibility

- assets/scss/base/form/_hint.scss
Added `form-hint--small` modifier to allow for smaller font (16px) hints.
> Added modifier for smaller form hints

- assets/scss/base/_buttons.scss
* Modifiers to space out sides of buttons that sit inline beside other elements.
* Modifiers to pad out sides of buttons with extremely short text.
> Modifiers for buttons that sit inline and buttons with short text

- assets/scss/base/_table.scss
* Modifier to reset font size for table TDs. Resets to our base font size of 19px.
* Modifier to space out above and below tables to provide enough gap between elements.
> Added table modifiers to reset font size and space out top and bottom

- assets/scss/base/_form.scss
Added border box to prevent padding from pushing `<input/>` and `<textarea/>` tags beyond their containers.
> Fixed inputs and textareas from spilling outside their containers in mobile

- assets/scss/_mixins.scss
- assets/scss/base/_layouts.scss
On request from Chris Moore so the skip link focuses on#content rather than service info.
> This work is backwardly compatible with teams with older versions of play-ui and new assets-frontend
* Related `play-ui` PR https://github.com/hmrc/play-ui/pull/41
* Related ticket NISP-1652
I have moved common parts into a `@mixin` and added a few overrides for selectors `#wrapper` and `#content` which brings the code into our `.sass` files rather than `govuk_elements`
I have commented, and will raise issues once merged.
> Nisp 1652 skip link focused to content

- assets/javascripts/modules/mask.js
- assets/test/specs/fixtures/mask-fixture.html
- assets/test/specs/mask.spec.js
Mask component now has an optional `data-mask-timer="<seconds_to_timeout>"` so that a masked secret that has been revealed can be hidden again once the time is up. Beautiful.
Here's one I made earlier. This times out in 2 seconds.
Amazeballs.
> [API-1086] Update to mask component to add optional timeout

- assets/javascripts/application.js
- assets/javascripts/modules/modalDialog.js
- assets/scss/_application-base.scss
- assets/scss/_mixins.scss
- assets/scss/base/_colours.scss
- assets/scss/modules/_modal-dialog.scss
- assets/scss/modules/_notifications.scss
- assets/test/specs/fixtures/modal-dialog.html
- assets/test/specs/modalDialog.spec.js
[AOSS-1057]
- adds accessible & responsive modal-dialog module CSS and JavaScript (_modal-dialog.scss, modalDialog.js)
- adds modal dialog module test specs and fixture
- includes update to modules/_notifications.scss
- adds '.highlight-message--light' variant
- black message on white background
- updates  '.highlight-message--dark' variant
- adds '.highlight-message--dark-text' to enable specific styling of child elements
> [AOSS-1057] add modal-dialog module

- assets/scss/modules/_modal-dialog.scss
* update modal dialog content 
* adding an "Open example" button to launch the modal dialog
* reduce size of example
> Update Modal Dialog component library page

- assets/scss/modules/_modal-dialog.scss
@mattpepper I was thinking something more like this...
* Description outside the experimental flag (as the description isn't experimental)
* And the content only needs to describe what goes where inside the dialog
> Update modal dialog example with more concise markup

- assets/javascripts/modules/registerBlockInputFields.js
Fixes on issues:
1 - Currently, whenever a radio button is selected the radio buttons in other button groups lose their white background too. 
[As GDS standards state](http://govuk-elements.herokuapp.com/form-elements/example-radios-checkboxes/), selected radio buttons should have white background.
2 - Currently, radio buttons don't lose focus whenever we focus on any other kind of component(i.e. textbox).
> Align radio button selected state with GDS standards and fix the radio button focusout

- assets/javascripts/modules/registerBlockInputFields.js
- assets/test/specs/fixtures/register-block-input-fields-fixture.html
- assets/test/specs/registerBlockInputFields.spec.js
This work involved:
- Fix the `registerBlockInputFields.js` file so that pre-selected checkbox/radio buttons have the class `selected` applied on load
- Tidy up the `registerBlockInputFields.js` 
- Remove brittle `JavaScript` that was relying on markup structure
- Add tests around this functionality
> Iht 1887 fix and tests

- assets/scss/_application-base.scss
- assets/scss/components/_auto-complete.scss
- Move autocomplete to `components` folder (this is the new name for modules), 
- add `.suggestions-input` selector to bring in work that was being applied from panels to autocomplete styles
- Add component-library comments
> AutoComplete - component library

- package.json
> **Note**: this issue impacts any page using the DataTables.net jQuery plugin. 
The DataTable.net plugin feature is added to table elements with the `js-datatable` class by the application.js, and uses `./javascripts/modules/enhancedTables.js` to configure default attributes.
The [DataTables.net](http://datatables.net) 1.10.11 release introduced a breaking change in `application.min.js` throwing an error which blocks JavaScript execution. The issue is believed to be related to the introduced functionality allowing a [DataTable to be created](http://datatables.net/upgrade/1.10) using:
* `$(...).dataTable()`, or
* `$(...).DataTable()`
> The difference between the two is that the first will return a jQuery object, while the second returns a DataTables API instance.
Whilst the previous minor …
> Downgrade datatables.net version

- assets/scss/base/_buttons.scss
- assets/scss/base/form/_form.scss
- assets/scss/base/form/_hint.scss
- assets/scss/base/form/_label.scss
- assets/scss/base/form/_text-input.scss
- assets/scss/base/form/_textarea.scss
These are now automatically prepended to modifier examples as per commit:
https://github.com/hmrc/component-library-template/commit/2ffb21bca4b37876c2053717689a9e69879465ea
This work removes the manual entries in comments.
> Update to copy to remove modifier classNames

- assets/scss/pages/_risk-triage.scss
I can't find these styles anywhere - marked as `//POTENTIALLY-NOT-IN-USE`
Issue raised:
https://github.com/hmrc/assets-frontend/issues/435
> Component-library - Marked as potentially not in use

- assets/scss/base/_links.scss
Added comments for links
**It appears that these styles don't apply `font-size` correctly**
> Component library - Links

- assets/scss/_application-base.scss
- assets/scss/components/_header.scss
Comments added and moved to components folder
Issue raised for `//POTENTIALLY_NOT_IN_USE` selectors https://github.com/hmrc/assets-frontend/issues/477
> Component library: Header

- CONTRIBUTING.md
- README.md
Contribution guidelines for committing work to assets-frontend. These are based on https://github.com/hmrc/mdtp-contributor-guidelines/blob/master/CONTRIBUTING.md and tailored to `assets-frontend`
- Added contributions
- Linked to CONTRIBUTING.md from README.md
> FE-106: contributing docs

- assets/scss/components/_external-markup.scss
Rename from external-markup--xsmall to external-markup.
There is no base class for --xsmall to be a modifier.
> Tidy up class name

- assets/scss/base/form/_textarea.scss
Added a `textarea--3-4` modifier to provide 75% width to textarea elements. The default width is often to small, and the 100% is too wide in certain cases.
> [API-965] Textarea modifier

- assets/scss/modules/_notifications.scss
* `background-position-y` not supported in Firefox - update to supported `background-position`
* `device-pixel-ratio` not supported in Firefox - add `background-size` as used in `device-pixel-ratio` media-query on `.highlight-message`
> Fixes notification icon alignment in Firefox

- assets/scss/_application-base.scss
- assets/scss/components/_app-info.scss
A module that describes an application. Typically used as an item among a list of applications. For example, a lists of Pending and Approved applications.
A module that describes an application's status.
> [API-965] Application info module

- assets/javascripts/modules/toggle.js
- assets/scss/_application-base.scss
- assets/scss/modules/_toggle.scss
A body of work to remove the `toggle.scss` work as the `toggle.js` can just use our `.hidden` selector.
- remove `toggle.scss`
- update `toggle.js` to sue the `hidden` selector.
There is also work associated on the TSV project
> TSV 37 update toggle js work

- assets/javascripts/modules/addRemove.js
- assets/test/specs/addRemove.spec.js
- assets/test/specs/fixtures/addRemove-fixture.html
A refactor on the add remove module
- bring template script functionality into JavaScript, 
- add ability to send in custom delete and add button text, 
- added ability to turn on/off delete functionality, 
- updated usage comments, 
- fix bug to do with order of inputs and deletion
- `data-can-delete="true"` to add delete buttons
- `data-delete-btn-text` to send in custom delete button text, this defaults to **Delete** and will only work when the
`data-can-delete="true"` is set
- `data-add-btn-text` to send in custom add button text, this defaults to **Add another redirect URI**
- `data-max` Maximum items allowed in the list
```
<div data-add-remove
data-max="5"
data-can-delete="true",
data-delete-btn-text="Delete Me"
data-add-btn-text="Add Me">
<ul class="add-remove__list" …
```
> Add remove refactor

- assets/scss/base/form/_errors.scss
- assets/scss/base/form/_form.scss
- assets/scss/base/form/_label.scss
- assets/scss/base/form/_radio-input.scss
Remove `for` attributes and `ids` for labels and inputs due to them causing problems with repeated code when using modifiers
> Component Library - remove for attribute on labels 

- gulpfile.js/tasks/watch.js
I have added the comp lib build to the javascript watch task mainly due to working on JavaScript in the component library without a service.
It may be the case that this is not needed when you are working on a service?
@hmrc/assets thoughts?
> Component Library: add the comp lib build to the javascript watch task

- assets/scss/modules/_hero.scss
Remove service-specific heading example text, and replaced with this:
> Changed example hero heading and subheading text to be generic

- assets/scss/modules/_epaye-statements.scss
* fix badly rendered icon flag `background-image`
* `:before` pseudo was using `fa-angle-left` ("\f104") from Font Awesome
* changed to space ("\00a0") and increased `padding-left` to pixel width of icon + 1
> [aoss-257] flag icon fix for statement data table

- assets/javascripts/modules/autoComplete.js
- assets/javascripts/modules/autoCompleteFactory.js
A body of work to enable the sending in of suggestions for the autoComplete via a `global` variable rather than interrogating a script tag via the id `suggestions`. 
This work is associated with https://github.com/hmrc/assets-frontend/pull/521
- update signiture of autoComplete to take an object of suggestions rather than using an `id` on a script tag
- update comments
> Auto complete data source refactor

- assets/scss/components/_auto-complete.scss
- component-lib.json
For the AutoComplete to display in the component library it needs to be accompanied with some mock data. In the examples case an array of countries:
```
<script type="application/json" id="suggestions">
[
{"title": "United Kingdom","value": "44"},
{"title": "Afghanistan","value": "93"},
{"title": "Sierra Leone","value": "232"},
{"title": "Wallis and Futuna","value": "681"}
]
</script>
```
This data was previously *hardcoded* via a partial in the component-library-template
The comment is sent in via the `ComponentData` attribute (`data` has already been taken) and will be added to the components page.
Once this is merged I will document this functionality in the Wiki
> Component library - component data

- assets/javascripts/modules/addRemove.js
- assets/test/specs/addRemove.spec.js
- assets/test/specs/fixtures/addRemove-fixture.html
Following updates to AddRemove JS component:
* Added more explicit comment to `data-can-delete` feature.
* Set default Add button text to "Add" (shouldn't be service-specific).
* Updated boolean expression evaluation in `deleteIsEnabled()` method to be more readable.
* Added jasmine tests to cover 3 different configurations of `data-can-delete`.
* Added Add/Remove HTML to fixtures for additional test.
> Updated AddRemove component

- assets/scss/base/_grid.scss
I've added one modifier to the grid component.
`.grid-layout--stacked` - stack columns in mobile
Issue raised to highlight design flaw that grid columns should be stacked in mobile. You may find it [here](https://github.com/hmrc/assets-frontend/issues/525)
> Grid Component Modifiers

- assets/javascripts/modules/addRemove.js
- assets/scss/components/_add-remove.scss
- assets/test/specs/fixtures/addRemove-fixture.html
Currently, adding a new item clones the first item in the list. However, the first item is not always a text input. Sometimes it's a read only field. Therefore, for cloning to work in all cases, the last item should be cloned, which is always a text input.
> Add/Remove Component Bug Fix

- README.md
- package.json
Using older versions of node and/or npm leads to conflicts with dependancies.
This specifies the versions we should be using in order to avoid those conflicts and the README's been updated.
There was also a missing dependancy for phantomJS when using a version of node greater than 5. That's been added.
> Specify versions of requirement and update README

- assets/javascripts/modules/addRemove.js
- assets/scss/components/_add-remove.scss
- assets/test/specs/addRemove.spec.js
- assets/test/specs/fixtures/addRemove-fixture.html
Currently, to add a new item, the AddRemove module clones a particular item in the list. It does this on click of the Add button. However, the cloned item might be in an error state, which results in copying over an error message and error class to the new element, as shown below:
For each instantiation of AddRemove module on the page, a cached template is created (against the index of that instance). To ensure the cached template is always clean (not in an error state), an empty item always needs to be available at the bottom of the list. Otherwise, there might only be one item in the list which is in an error state and cannot be cloned. This limitation is currently due to the fact that my usage of AddRemove only provides server-side validation on inputs. Further work will be needed to …
> [API-1370] Added caching of cloneable item HTML

- assets/scss/base/form/_label.scss
Background covered in this issue: fixes #539
Essentially, `.top-aligned-input` was useless, being overridden due to `.block-label input`. To work, it needed to be moved to `.block-label input.top-aligned-input`.
> Moved .top-aligned-input to .block-label input.top-aligned-input

- assets/scss/base/_links.scss
- assets/scss/base/form/_form.scss
- package.json
The [`2.3.x` release of `gulp-sass`](https://github.com/dlmanning/gulp-sass/releases/tag/v2.3.0) [bumps the version of `node-sass`]() (which in turn bumps `libsass`) which makes `@extend` stricter.
This in turn meant that our builds were breaking because errors were being thrown that weren't previously...
- Bump gulp-sass to `^2.3.0`
- `@import` instead of `@extend` the `external-link-default` mixin in `_links.scss` as it's not a placeholder
- Fix type on `contain-floats` in `_form.scss`
> Update gulp-sass and fix resulting errors

- assets/javascripts/application.js
- assets/javascripts/modules/dynamicGaTags.js
- assets/test/specs/dynamicGaTags.spec.js
- assets/test/specs/fixtures/dynamic-ga-tags-fixture.html
Currently, our `stageprompt.js` script binds click events to all `data-journey-click` tags in the page, sending Google Analytics (GA) track events.
In some instances, the GA event applies to the submit button of a form. The value of the `data-journey-click` attribute is `<category>:<event>:<label>`. I needed to alternate the value of `label` depending on a radio button selection.
I created a new JS module, `dynamicGaTags`, to update a `data-journey-click` attribute based on the radio button selection.
```
<form id="container1" action="/some/amazing/endpoint" data-journey-dynamic-radios>
<fieldset>
<label>
<input type="radio" id="approveBtn" name="radioBtn" value="APPROVE" data-journey-val="Approved" checked/>
Approve
</label>
<label>
<input type="radio" id="rejectBtn" name="radioBtn" …
```
> [API-1355] Library to dynamically update GA event tags

- assets/scss/components/_notifications.scss
Removed the extra padding bottom added to the 'highlight-message--light' and 'highlight-message--dark' classes. This should ensure that the highlight messages have equal padding top and bottom
Before: 
After:
> YTA-1864 - Remove extra padding bottom from the light and dark themed highlight messages

- CONTRIBUTING.md
The guidelines had previously not included any mention of the new component library so they've been updated.
I also updated what to include in the PR description. A title's not necessary.
> Add component library to contributing guidelines

- assets/scss/base/form/_form.scss
_form.scss in govuk_elements sets -webkit-appearance: none on all elements using .form-control, causing the dropdown button to disappear on Chrome/Safari.
This PR fixes the class on the select element.
Before:
After:
> Fix .form-control select on Webkit

- assets/javascripts/modules/ajaxCallbacks.js
- assets/javascripts/modules/ajaxFormSubmit.js
Progressive enhance to API subscription module to use ajax to subscribe for an API and displaying various state like loading & error. The part of this story relies on backend changes in third-party-developer-frontend as well on some asset-frontend components e.g toggle button, error notification & ajax waiting state  
The challenge here was to use existing `ajaxFormSubmit` & `ajaxCallbacks` components and adapt it to our need. Existing functionality use `link` with parameters and runs some business logic on backend  to switch to correct state of the buttons when user click on the link.
Converted `link` to `form` and used `hidden` fields for parameters. Additional information is passed as `data` attribute on the form to run business logic checks on client side and update DOM accordingly. …
> [API-1452] Ability to subscribe to an API (JS version)

- assets/javascripts/modules/ajaxCallbacks.js
- assets/scss/_application-base.scss
- assets/scss/components/_waiting.scss
Assets frontend currently don't have any loading/waiting component to show busy state. And as part of story number [API-1452] UI need to show waiting/loading state when user clicks on subscribe button.
We cannot use `<img>` tag with `src` because the asset-frontend is loaded as a dependency in other apps and developers need to work out correct `path` in order to use it.
Created a new `waiting` component with `'images/loading.gif'` as background image.
```
<span class="waiting"></span>
```
> [API-1585] Add waiting/loading component

- assets/javascripts/validation/form.js
- assets/test/specs/fixtures/form-fixture.html
- assets/test/specs/form.spec.js
Bug exposed by grouped form elements when part of group is hidden
When a form validation error is occurs where:
1. the form is bound to generic validation via the `.js-form` selector
2. and some form elements are `:hidden`;
3. the `:hidden` elements value attribute is "cleared" via $(*element*).val('') 
This behaviour is incorrect for both `radio` and/or `checkbox` elements where the value should **not** be cleared.
In the shown example, the form:
* validates that the required number of 'checked' elements in the group is correct
* has two `radio` elements in the group, which are `:hidden` by a `checkbox` toggle element
When the form is submitted:
1. without the required number of elements selected
2. *and* the `radio` elements are `:hidden`
3. the bug results in:
a. the `radio:hidden` …
> [PE-1926] validation bug for radio and/or checkbox elements

- assets/javascripts/modules/ajaxCallbacks.js
Subscription counts are not updated when user subscribe to an API. This bug was introduced as a part of story no [1452](https://jira.tools.tax.service.gov.uk/browse/API-1452). For referecne please check merge request [https://github.com/hmrc/assets-frontend/pull/560]
> Update subscription count from API response

- assets/images/icon_printer.svg
- assets/scss/base/_icons.scss
- assets/scss/components/_header.scss
* Add print icon in SVG format
* Add style to display print icon
* Add print only styles to `transaction-banner--complete` class for a more printer-friendly version. The original was white text on a large turquoise background.
Icon:
screen rendering of  `transaction-banner--complete`:
print rendering of  `transaction-banner--complete`:
> GG-656: Print icon and style

- assets/scss/base/form/_text-input.scss
Component library screenshot.
Identity Verification frontend requirement to add a **£** symbol visually within a number input field.
I understand this will be useful for other services too.
> PE-1968: Styles to add pound currency symbol to number input fields

- package.json
For hmrc prototype pulling assets-frontend in, remove napa from dependencies, remove npm run script, white space fix
> update devDependencies to dependencies 

- assets/javascripts/modules/ajaxCallbacks.js
- assets/scss/components/_toggle-button.scss
As part of API-1452 story we need to handle error state and it visual style should be same as `error-notification` component.
Adding `error-notification` wasn't a quick win here as it was not visually align with toggle button.
Refactored toggle button to be wrapped inside `toggle` class and added `error` & 'btn' as sub modules to fix style and layout issue.
```
<span class="toggle">
<span class="error-notification inline-block toggle__error">Error state</span>
<a href="#" class="toggle__button">link</a>
<button class="toggle__button">link</button>
<span class="toggle__button toggle__button--active">on</span>
<span class="toggle__button toggle__button--inactive">off</span>
<span class="toggle__button toggle__button--disabled">disabled</span>
</span>
```
> [API-1586] refactored toggle button & added error & disabled state

- assets/scss/base/form/_hint.scss
Long text after form hint list items wraps below the bullet point / green tick, rather than below the first line of text. This changes the behaviour from the former to the latter.
> GG-895: Indent wrapped text on form hint list items.

- assets/scss/base/layouts/_layouts.scss
This fixes the fact that `<p></p>`s within `.content__body` were having their margin ignored.
> Remove "px" from em mixin

- assets/scss/components/_auto-complete.scss
for better mobile display, so not too close to the border.
> GG-885: Tweak suggestions clear button position

- assets/javascripts/modules/ajaxCallbacks.js
- assets/javascripts/modules/ajaxFormSubmit.js
- assets/javascripts/modules/mask.js
- assets/test/specs/fixtures/mask-fixture.html
- assets/test/specs/mask.spec.js
The `Mask` component should display a string of `•••••••••••••••••••` and reveal the underlying string when the user clicks a trigger.
The current implementation does not support password authentication in order to reveal secret. 
The other issue is that backend service expect password as header instead of form body or querystring.
Added a toggle target as an intermediary step. If `data-mask-toggle-target` attribute is set on mask control, its then toggle target selector on click. After that It's then down to the target component to `trigger` event on `mask` component to reveal secret. 
The form use `ajaxFormSubmit` to submit request. Extend it support custom headers from input field. It now looks for input with `data-ajax-header` attribute to map to header.
On success callback, it …
> Authentication support for mask component

- assets/scss/_application-base.scss
- assets/scss/components/_organisation-logo.scss
Create component lib documentation.
Move file into components.
Remove redundant padding declaration.
> FE-167 Document modules/_organisation-logo.scss

- .stylelintrc
- assets/scss/_mixins.scss
- assets/scss/base/_icons.scss
- assets/scss/base/_normalize.scss
- assets/scss/base/_table.scss
- assets/scss/base/form/_form.scss
- assets/scss/base/form/_text-input.scss
- assets/scss/pages/_payments.scss
- gulpfile.js/tasks/sass.js
- add `"property-no-vendor-prefix": true` rule
- remove any vendor prefixes 
- disable stylelint in [_normalize.scss](https://github.com/hmrc/assets-frontend/blob/FE-190-add-no-vendor-prefix-stylelint/assets/scss/base/_normalize.scss)
- explicitly set vendor prefixing in autoprefixer to `['last 2 versions', 'IE >= 8']`
```
.arrow--expand {
transform: rotate(90deg);
transition-duration: 0.2s;
}
```
```
.arrow--expand {
-webkit-transform: rotate(90deg);
-ms-transform: rotate(90deg);
transform: rotate(90deg);
-webkit-transition-duration: 0.2s;
transition-duration: 0.2s;
}
```
> Fe 190 add no vendor prefix stylelint

- assets/scss/modules/_help-contents.scss
The Jira story was to document `_help-contents.scss` for the Component Library and migrate into components, but the styles are no longer used anywhere.
The styles used to be used in `help-frontend` but has been removed from there, and also removed from 2 prototypes which used it, `hmrc-businesstax` and `hmrc-payments`.
assets-frontend issue created to address establishing whether the classes are still used:
https://github.com/hmrc/assets-frontend/issues/612
> FE-165: Mark _help-contents.scss as possibly not in use

- assets/scss/base/_buttons.scss
- assets/scss/base/_links.scss
This fixes a button that's styled to look like a link being white.
> Hotfix button link style

- assets/scss/_application-base.scss
- assets/scss/base/_images.scss
… that retains clarity on retina screens and at zoomed in levels.  For this end, we need to constrain images at a maximum of 100% of their containers width.
What was:
becomes:
> PE-2200 : Setting img max-width to 100% of container element.

- .stylelintrc
Stylelint rule `"declaration-block-semicolon-newline-after": "always-multi-line"` to enforce multiline declaration blocks
```
.example {
margin-top: 2em;
}
```
Not:
`.example {margin-top: 2em;}`
> add rule to enforce newlines after semi colons

- assets/scss/_application-base.scss
- assets/scss/components/_report-error.scss
Component Library documentation for report-error, used for 'Get help with this page' form.
This will not demonstrate the functionality of the component until we have worked out how to use our JS in the library, and possibly mock external dependencies such as the ajax file load which this module typically uses. Issue for resolving this:
https://github.com/hmrc/component-library-template/issues/19
> FE-169: Document _report-error.scss and move into components

- assets/scss/_application-base.scss
- assets/scss/base/form/_text-input.scss
- assets/scss/components/_datatables.scss
- assets/scss/modules/_datatables.scss
- documented data tables
- moved global placeholder webkit styles into form base file
- marked `.controlpanel` as `//POTENTIALLY NOT IN USE` as it cannot be found in repo searches
issue raise #629
> Component library datatables

- README.md
rejig of the README instructions for developing with the component library template, the information that you are required to npm link the component library template before you run the`npm run comp-lib:watch` watch command was missing.
I have also moved the information about setting up and using the watch task to be after the initial manual instructions for linking the `component library template`, which feels like a more natural position.
> README instructions for developing with the component lib

- assets/scss/base/_buttons.scss
`.button--spaced` and `.button--padded` weren't in the modifiers list of buttons.
> Add spaced and padded buttons to comp lib modifiers list

- assets/scss/_application-base.scss
- assets/scss/components/_footer.scss
- assets/scss/modules/_template-footer.scss
- moved what looks like small tweaks to the `footer` into a `base/footer` file
- marked the majority of work in `components/footer` as `//POTENTIALLY NOT IN USE` as they cannot be found in repo searches
- moved work from `modules/template-footer` into `base/footer` as this was an override
There is no actual component library documentation here this is just a cleanup and deprecation marking PR
issue raise #626
> Component library footer

- component-lib.json
Added the flag `Background:` to allow developers to make the element that contains component examples have a dark background.
> add component library Background custom tag

- assets/scss/components/_flag.scss
- split flag right out to its own modifier 
- added `Background: dark` to left flag example
- added `Background: dark` to right flag example
fixes #566
> Added Background: dark custom tag to flag comments

- assets/scss/components/_navigation.scss
On finding that it was only being used in a few old projects we've decided to deprecate the `.page-navigation` styles. They will be removed in an upcoming version.
I also reordered the file and the display of the page so the deprecated styles are less prominent.
> Mark .page-navigation as deprecated and reorder file

- assets/javascripts/modules/ajaxCallbacks.js
Service specific ajax callback is updated to select correct element from the page based on the category group and update no of subscriptions message.
> Update subscription counts in correct category 

- assets/scss/base/_buttons.scss
- assets/scss/base/_grid.scss
- assets/scss/base/_icons.scss
Maintains the half width of the grid on mobile displays with an additional style rather than stacking elements. This is to maintain a consistent visual style between devices.
Also brings other code in-line to use the standard media query in the full width button and calendar icon.
Demo in the Component library:
> TCS-812c updating media queries in calendar icon

- assets/javascripts/validation/form.js
- assets/test/specs/form.spec.js
Links in an `error-summary` list with multiple errors listed require *two* clicks to:
1. scroll the associated invalid form element
2. setting the associated element state as focused
To reproduce:
1. Goto a page with a form with client validation rules for multiple fields
2. Submit the form with invalid data
3. On the displayed `error-summary` link list click a link
The page *does not* scroll to and set the focus state on the invalid form element that the clicked `error-summary` link is associated with.
The page scrolls to and sets the focus state on the invalid form element that the clicked `error-summary` link is associated with.
Override the `$.validator.defaults.onfocusout` handler passed to `$formElem.validate` by adding the validation setting:
```JSON
{
onfocusout: false
}
``` …
> # Fix validation error summary link behaviour

- styleguide.md
Added feedback box information to the homepage of the component library which is being linked from the feedback box.
This is related to PR [#31](https://github.com/hmrc/component-library-template/pull/31) on the component-library-template
> [FE-222] Updates to component lib homepage

- package.json
Number type input fields still display increment / decrement control in Firefox when the `.input--no-spinner` rule is applied (as shown below).
Firefox doesn't recognise `appearance` property value of `textfield`, as applied by `.input--no-spinner` and `gulp-autoprefixer` versions pre 3.0.0. does not add the `-moz-appearance` property in the application.min.css build. 
Update `gulp-autoprefixer` to most recent major version (3.0.0) or above.
> Update gulp-autoprefixer to 3.0.0

- assets/javascripts/modules/validatorFocus.js
'validatorFocus' module was throwing exception when error summary contained a link without 'data-focuses' attribute (a normal link which should just navigate to a page).
Added check to ensure the attribute exists. Normal link behaviour is restored when a link doesn't have 'data-focuses' attribute.
> CATO-3714: Fixing the problem with 'validatorFocus'.

- assets/scss/_shame.scss
Currently heading styles cannot be applied to `p` elements as `.content__body p` is more specific.
I have added `p.h*-heading` and `p.heading-*` to `_shame.scss` in order to temporarily resolve this issue. I'll add a note to remove this code on the relevant issue once it has been merged.
> TAI-1415 adding paragraph workaround to _shame.scss

- .travis.yml
Some of our dependencies rely on a newer version of node that we were using. This was therefore breaking our build.
This PR updates the version of node to reflect what's on our internal build boxes.
> Update the node version used on travis

- assets/govuk_elements/public/sass/service-design-manual/helpers/_breadcrumbs.scss
- assets/scss/components/_breadcrumb.scss
The https://assets.digital.cabinet-office.gov.uk/ domain is being decommissioned on Oct 1st. This work replaces the two urls we use with data-uris.
> Replace gds urls with data uri

- assets/scss/components/_accordion.scss
This change is to support grouped API endpoints within the accordion for Self Assessment on the API Documentation Index page - the endpoints within a group (with the exception of the final endpoint of the group) will have the new `.accordion__body__row--no-border` style applied along with the normal `.accordion__body__row` style in order to remove the bottom border from appearing between each endpoint of the group
> APIS-651 Styling change to support grouped endpoints 

- assets/scss/components/_accordion.scss
In the documentation the 'hidden' class is hard coded. this prevents the accordions from opening when js is disabled
> hardcoding "hidden" class

- assets/javascripts/modules/reportAProblem.js
**Issue:**
Users are prompted to email an unsupported account when a deskpro message fails to submit.
**Action:**
Shorten message to "Please try again later".  Affects payments-frontend, ei-frontend and assets-frontend.
**Ownership:**
Decided by BTA after consulting Digital Contact.
> OPS-420 : email address - ‘hmrcsupport@tax.service.gov.uk.’ not to be used.

- assets/javascripts/modules/toggle.js
`visible-javascript-on` has been replaced with `js-visible`
> update deprecated className in Js example

- assets/scss/components/_datatables.scss
In Datatables, all headings are given a pointer cursor, even those not sortable. Where the javascript adds the class `.sorting_disabled`
Exclude these from the cursor styling as another visual queue that the heading is not clickable.
> Leave default cursor on disabled headings

- assets/javascripts/modules/autoComplete.js
On a page with autoComplete, when a user selects "Dominican Republic", there are three possible country codes that match. To view the issue, make then hidden <select> visible, then proceed as follows. User selects the second or third option, as soon as they have selected, and then blurred away from the autocomplete input,  the "isMatchingSuggestion" function fires, and updates the  select with the first matching option.
In the attached gif, note how the select changes when focus is lost from the autocomplete input
adding an attribute to the autocomplete input enables retention of both text value and associated code.
> fix autoComplete bug when Dominican Republic is chosen

- assets/scss/base/_grid.scss
Removes edge gutters to allow horizontal alignment with neighbouring content. Prevents the indenting which otherwise happens when using the grid.
> Grid layout modifier - nogutter

- .gitignore
- README.md
- gulpfile.js/config.js
- gulpfile.js/tasks/vrt.js
- gulpfile.js/util/backstop/backstop.template.json
- gulpfile.js/util/backstop/buildScenarios.js
- gulpfile.js/util/backstop/configGenerator.js
- gulpfile.js/util/mergeObj.js
- package.json
Add Visual Regression suit to test the Component Library to help developers when making style changes.
- `backstop.json` config creation from `Component Library` files
- Serve `Component-Library` locally
> Visual regression tests

- assets/javascripts/modules/autoComplete.js
Updates autocomplete where select input is used as source for suggestions
If a select input is being used as the source of the suggestions and it has a selected option on page load, the autocomplete input does not populate.
Added a call where if the select is being used as the source for suggestions any existing value is rendered to the autocomplete input.
> Allow setting of existing value to autocomplete select input

- assets/javascripts/modules/autoComplete.js
This improves the accessibility of the autocomplete component, specifically on iOS
Fixes #724 
This tackles the issue in a few ways:
1. Fixing some of the aria attributes - these weren't defined in the best way and so weren't working as expected.
2. Allowing VoiceOver to navigate the suggestions list
3. Slight change to the copy used
4. Preventing the suggestion list from closing on blur (added a tab key check to close it when tabbing off to next input to maintain keyboard behaviour). This prevents the suggestions list from closing when a VoiceOver user is navigating via touch or swipe gestures.
5. Ensure when a suggestion is selected, the input is focussed.
> Auto complete accessibility ios

- assets/javascripts/modules/toggleDynamicFormFields.js
Currently when the user triggers the hide attribute, the javascript in toggleDynamicFormField.js file finds text fields and deletes the contents of that field. This doesn't work if the input field is of type number.
In our service we have income pages that take the amount in input fields of type number. Currently in our service if user enters a number and then clicks "No" to cancel, the value in the field isn't cleared and hence the validation prevents the user from continuing until they manually clear the field.
The new code finds the number field as well as text field and clears that too.
Please see attached gifs.
> added javascript to toggleDynamicFormField to clear numeric field

- .gitignore
- assets/error_pages/401.html
- assets/error_pages/403.html
- assets/error_pages/404.html
- assets/error_pages/500.html
- gulpfile.js/config.js
- gulpfile.js/tasks/build.js
- gulpfile.js/tasks/default.js
- gulpfile.js/tasks/error-pages.js
- package.json
Error pages for nginx weren't being added to the final `zip` that gets deployed.
The assets paths in the error pages were also relative so the assets weren't loading if you were on a non-existent page (i.e. `/broken-page` would try and load `/broken-page/stylesheets/application.min.css`)
* Updated the govuk-template paths in the error files.
* Added an `error-pages` gulp task that copies the files to the correct output directory (depending on the `process.runmode` set by either `npm start` or `npm run build`) and updates any paths based on the version being built
> [WEBOPS 4032] Add nginx error pages to the output directories

- assets/error_pages/401.html
- assets/error_pages/403.html
- assets/error_pages/404.html
- assets/error_pages/500.html
The URLs for GOV.UK Template assets were missing `/assets` resulting in 404s
Update the URLs to point at the right files.
> Fix GOV.UK template url for error pages

- gulpfile.js/util/backstop/backstop.template.json
- gulpfile.js/util/backstop/onReady.js
Some of our components need to be interacted with before a screen capture is performed
- Details elements opened
- AutoComplete with text in the input
- Add remove with more than one input
- Form errors fired
Use the global `onReady` functionality available via `backstopJS` to interact with components when you are on the relevant page
- This is relying on the `label` of a page as defined in the `scenarios` backstop object which is prior work that potentially [needs refactoring](https://github.com/hmrc/assets-frontend/blob/master/gulpfile.js/util/backstop/buildScenarios.js#L55)
- This is tightly coupled to the Component Library and this work will be potentially refactored out
> Sdt 162 add interaction for vrt

- gulpfile.js/tasks/default.js
- gulpfile.js/tasks/watch.js
We had an eslint error being reported on a trailing comma, this fixes that error
> Lint config files before watch task and fix error

- CONTRIBUTING.md
The contributing guidelines were poorly structured, hard to read, and difficult to follow. 
They also only outlined a step-by-step process which was outdated and didn't represent what was actually happening.
The new guidelines:
* have a much clearer structure, 
* cover more than just a process
* each section is much more concise, linking off to related info
> Simplify the contributing guidelines

- gulpfile.js/tasks/test.js
- gulpfile.js/tests/mergeObj.test.js
Failing gulp task tests aren't breaking builds on CI
From https://travis-ci.org/hmrc/assets-frontend/builds/206974831#L782:
Add a bail flag to tape to make sure that the build fails on CI
From https://travis-ci.org/hmrc/assets-frontend/builds/206988745#L679
> Add bail to break CI builds when tests fail

- CHANGELOG.md
- gulpfile.js/util/backstop/onReady.js
When running visual regression tests the [Youtube video player](http://hmrc.github.io/assets-frontend/section-youtube-player.html) was failing due to differences on the static between `npm run vrt:baseline` and `npm run vrt:compare`. 
Allows the youtube video player visual regression tests to pass.
We now apply a div in the Youtube container which is then styled to cover the player with a large black rectangle so the test always passes.
> Fixed the youtube failing visual regression test

- .travis.yml
- CHANGELOG.md
- gulpfile.js/tasks/build.js
- gulpfile.js/tasks/changelog.js
- gulpfile.js/tests/changelog.test.js
- package.json
Having added a `CHANGELOG.md` we need a way to remind contributors to update it when they make a pull request.
Add a gulp task that breaks the build if `CHANGELOG.md` hasn't been updated as part of the pull request.
- Get the commit being built
- Diff the commit against master for the names of the files that have changed
- Check to see if `CHANGELOG.md` appears in that list and throw an error if it does
**Failing**: https://travis-ci.org/hmrc/assets-frontend/builds/207461966#L1140:
**Passing**: https://travis-ci.org/hmrc/assets-frontend/builds/207466855#L1141
> Check that the change log has been updated as part of a PR

- CHANGELOG.md
- gulpfile.js/tests/changelog.test.js
2 lines of JS were not adhering to the lining rules for the project.
Within the test for the js file used to inspect the changelog, there were lint rule issue (gulpfile.js/tests/changelog.test.js):
* A dependency was unused.
* Syntactic style wasn't correct for parentheses spacing
I removed the import of the unused dependency & added the whitespace need to allow the anonymous function to pass.
> Simples fixes to align js to linter rules

- CHANGELOG.md
- gulpfile.js/tasks/browserify.js
- package.json
Our `application.min.js` has some absolute paths we wish to convert to id's in production.
On production builds only use [bundle-collapser](https://github.com/substack/bundle-collapser) a plugin for browserify that has been built for this job.  
> convert bundle paths to IDs to save bytes in browserify bundles
Also make `{fullPaths: false}` in `browserify`:
<blockquote>
--full-paths
Turn off converting module ids into numerical indexes. This is useful for
preserving the original paths that a bundle was generated with.
</blockquote>
VRT tests pass
> NOTE: this is shown in none minified mode for illustrative purposes only
> Add bundle-collapser to convert absolute paths to ids in bundled JavaScript

- CHANGELOG.md
- assets/javascripts/modules/ajaxCallbacks.js
- assets/test/specs/ajaxCallbacks.spec.js
The ajax form on the collaborators screen of the Developer Hub currently passes an email address in the action url.  
We are cleaning this up to ensure emails are only passed in the request body.  The change updates the form in the ajax response to use a hidden input in a data-container instead.
> Remove email from APICollaboratorResponse url 

- CHANGELOG.md
- gulpfile.js/tasks/changelog.js
The `CHANGELOG.md` check in the build tasks was failing on Jenkins due to missing master as a refspec.
Use Jenkins' environment variables to make sure references to commits exist.
> Fix changelog check with jenkins env vars

- CHANGELOG.md
- gulpfile.js/tasks/changelog.js
- gulpfile.js/tests/changelog.test.js
The `CHANGELOG.md` check fails even if no files have been changed. This fails the build when run on non-PRs in CI.
Pass the `CHANGELOG.md` check if there are no files changed since the last commit.
> Pass the change log check when no files have been changed

- CHANGELOG.md
- README.md
The documentation specifies a minimum version of Node to be used when working on assets-frontend, however there is also a maximum version and a single supported version. 
The supported version is the version used on the build servers. Node v4.4.5
Updating the README.md to specify Node v4.4.5 (and update the CHANGELOG.md) fixes #774
> Specify correct node version in the README.md file

- CHANGELOG.md
- assets/scss/components/_header.scss
Headings in Transaction Banners were supposed to be White but any "article h1" was being overridden to Black
This: http://hmrc.github.io/assets-frontend/section-header.html should now be this: https://govuk-prototype-kit.herokuapp.com/docs/examples/confirmation-page
I explicitly set the header class to be White
Screenshot from running **npm run vrt:baseline** before
and after
> Made headers in transaction banners default to White

- CHANGELOG.md
- assets/scss/components/_tabs.scss
Fixes #778 
The component library implementation of tabs doesn't enable the behaviour which allows deep-linking to a tab other than the initial tab.
Designers and developers are  therefore unaware that this behaviour is possible with the assets frontend tabs control.
Navigating to the assets frontend with a fragment that references a tab should open that tab on page load e.g.
http://hmrc.github.io/assets-frontend/section-tabs.html#tab3
Should open with Tab 3 open
add the `js-hash-selected-tab` class to the div with the `data-tabs` attribute eg
```<div data-tabs class="js-hash-selected-tab">```
> Enabled targeting of a tab component via URL fragment in the component library

- CHANGELOG.md
- gulpfile.js/config.js
- gulpfile.js/tasks/lint.js
- package-lock.json
See #782 
Modernizr is adding an [`arrow` class](https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/es6/arrow.js) to the `html` tag which applies a [12px width](https://github.com/hmrc/assets-frontend/blob/4e6b261a2aa78ff0f2ea021c3f9c9a954d84043f/assets/scss/base/_icons.scss#L22) to the entire page.
See #782 
Excluded the `arrow` test in the modernizr config.
Fixes #782
> Ignore modernizr arrow

- .travis.yml
- CHANGELOG.md
- gulpfile.js/tasks/changelog.js
- gulpfile.js/tests/changelog.test.js
A test was failing when running on node 4.8.4
Fix the changelog test to explicitly reject with an error when not given a command.
> Build successfully against node 4.8.4 

- CHANGELOG.md
Moved items in  `Unreleased` section to a new `2.247.0` section.
> Update CHANGELOG for release 2.247.0

- CHANGELOG.md
- gulpfile.js/tests/BuildScenarios.test.js
- gulpfile.js/tests/configGenerator.test.js
- gulpfile.js/util/backstop/BuildScenarios.js
- gulpfile.js/util/backstop/configGenerator.js
When running a build on the current LTS version of node, the build fails due to various errors. Primarily, failing tests due to a change in error strings being returned.
Refactor out code to return our own error messaging, and test for those strings instead.
> Refactor unit tests to allow builds on node 4.8.4 and 6.11.1 simultaneously

- CHANGELOG.md
- gulpfile.js/tasks/comp-lib.js
Running `gulp` causes a silent failure.
Run the `cb` argument, which runs the server.
> Fix builds silently failing

- CHANGELOG.md
- gulpfile.js/tasks/vrt.js
- package.json
VRTs currently offer no logging levels, and the output can be confusing.
Allow a `--quiet` option to be passed in when running VRTs which reduces logging verbosity and makes things clearer.
> SDT-306 - Optional quiet logging for VRT baseline runs

- CHANGELOG.md
- gulpfile.js/tasks/build.js
After the refactoring of gulp tasks, the sass job doesn't build the production stylesheets during the [`build`](https://github.com/hmrc/assets-frontend/blob/b4ce7e2/gulpfile.js/tasks/build.js) job.
Because the sass task is being run as a dependency of the `test` task, the `global.runmode` is set as the default `dev`. Due to this, the sass task doesn't minify the styles or put them in the `assets/dist` directory ready to be zipped and deployed.
By explicitly calling the `sass` task as a step in the `build` task it picks up the `global.runmode = 'prod'` setting and builds the styles for production.
The `sass` task is being run twice as it's still a dependency of the `test` task. Ideally, the `sass` task would only be run once and then a separate minification step would be run for …
> Rerun sass task in prod mode for CI

- CHANGELOG.md
- assets/govuk_elements/govuk/public/sass/_colours.scss
- assets/govuk_frontend_toolkit/stylesheets/_colours.scss
- assets/scss/base/_colours.scss
This pull request includes:
• adding $discovery-colour and $live-colour variables
• updating semantic colour variables to match gov.uk - only affects alpha and beta banners, link :hover and active states and error colour
The purpose of this is to bring assets up to date and inline with gov.uk so that all services use the latest colours to reduce inconsistencies.
This won't break anything, but will update colours that bump to latest version of AF
Inconsistencies in colours
Link to colours in GOV.UK frontend toolkit
https://github.com/alphagov/govuk_frontend_toolkit/tree/master/stylesheets/colours
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/colours/_palette.scss
Alpha and Beta banners on GOV.UK
http://govuk-elements.herokuapp.com/alpha-beta-banners/
> Add discovery and live colour variables and update semantic colours

- CHANGELOG.md
- assets/govuk_frontend_toolkit/stylesheets/design-patterns/_buttons.scss
To update button mixin padding and adding outline css. The padding updates increases padding and matches GOV.UK styles. The addition of outline: introduces a Safari focus issue, as mentioned in GOV.UK frontend toolkit - https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/design-patterns/_buttons.scss#L33-L34
Buttons sizing out of sync with GOV.UK styles
Update padding and add in outline css
> Update button mixin

- CHANGELOG.md
- assets/scss/base/_helpers.scss
Fixes issue #727
Removes important clauses which prevented VoiceOver from reading visually hidden copy inside links. Aligns code with GDS Elements.
> Update visually hidden class to align with GDS Elements

- CHANGELOG.md
- assets/govuk_elements/public/sass/elements/_forms.scss
- assets/scss/base/form/_form.scss
Updating base with .form-control styles which were missed in https://github.com/hmrc/assets-frontend/pull/812 which override those changes.
> Missed updating .form-control styles in base file

- CHANGELOG.md
- assets/scss/components/_notice-banner.scss
The existing styles for the notification banner don't account for pseudo classes on the anchor. 
That means the default styles make the anchor melt into the banner. 
This commit adds styles for those pseudo classes.
> Notification banner styles

- CHANGELOG.md
- assets/components/account-menu/_account-menu.scss
Problem
A number of services have use of a full width banner found in the new template.
Solution
Add styling to the banner added into frontend-template-provider
Screenshot
> MTA-2832 - Add styling for frontend-template-provider full-width banner

- .gitignore
- CHANGELOG.md
- assets/components/check-your-answers/README.md
- assets/components/check-your-answers/_check-your-answers.scss
- assets/components/check-your-answers/check-your-answers.html
- assets/scss/_application-base.scss
Introduction of new styling, derived from the GOV.UK design pattern [here](https://www.gov.uk/service-manual/design/check-your-answers-pages)
A number of services have the same requirement when developing linear journeys, for an accessible and responsive confirmation page. Rather than define the relevant styling locally to services, we're adding to the assets-frontend library for consistent use across services.
The new sass partial we've introduced is taken directly from the GOV.UK service design manual example. No changes have been made.
The screenshot below is taken directly from the GOV.UK service design manual, and an illustration is now included in the generated component library.
> TAI-3083 : Introduce styling for check-your-answers summary content

- CHANGELOG.md
- assets/scss/base/form/_form.scss
Currently all 3 date inputs are the same width, despite the 3rd input with class .form-group-year having a set width of 70px. This is because of incorrect hierarchy, so I have move this style below so that the width is assigned correctly.
As default Firefox displays a value adjustment arrows for input type="number" which allow the user to adjust the value within the input.
- Moved .form-group-year down, so the larger width is assigned correctly
- Added in appearence: textfield to remove value adjusters in Firefox
- Update value of input width from 56px to 50px inline with GOV.UK
> Minor input type="number" updates

- CHANGELOG.md
- gulpfile.js/util/pattern-library/lib/renderPagesFromTemplate.js
The github pages domain is a subdirectory (i.e. http://hmrc.github.io/assets-frontend/) but the template's asset paths in the template are root absolute.
Add a `pathPrefix` that gets passed into the template when the gulp task is built in `prod` mode (i.e. on CI).
> Add pathPrefix for template

- CHANGELOG.md
- gulpfile.js/util/pattern-library/lib/renderPagesFromTemplate.js
The pattern library is run as a separate job on our jenkins so `global.runmode` doesn't get set to `prod`.
Use `NODE_ENV` instead and run the pattern library on CI with that instead:
`NODE_ENV='prod' npm run pattern-library`
> Use NODE_ENV for building pattern library on CI

- CHANGELOG.md
- assets/components/header/README.md
- assets/components/header/_header.scss
- assets/components/header/header--signed-in.html
- assets/components/header/header.html
- assets/scss/_application-base.scss
As the new design system is available, we are porting components from component library.
Header component is not available in design system.
Port header component from component library.
> HMRC header component

- CHANGELOG.md
- assets/components/header/header--signed-in.html
- assets/components/header/header.html
The language select is missing a pipe (`|`) between the words "English Cymraeg" and the word "English" is a link.
Added a pipe and removed the link from the word "English"
> Fix the language toggle example

- CHANGELOG.md
- gulpfile.js/tasks/changelog.js
- gulpfile.js/tests/changelog.test.js
Even if only a README markdown has changed the build fails due to untouched CHANGELOG.md
Whitelist README.md files so build won't fail
> whitelist README.md files from CHANGELOG check

- CHANGELOG.md
- assets/components/account-menu/README.md
- assets/components/header/README.md
- assets/patterns/404-page/README.md
- assets/patterns/shutter-pages/README.md
- gulpfile.js/util/pattern-library/lib/parseDocumentation.js
- gulpfile.js/util/pattern-library/macros/wip.html
WIP banner code is duplicated across markdowns.
Introduce a macro to centralise the markup and to provide a reusable component.
> Implement wip macro and replace the code duplications

- README.md
* The README.md is far too verbose making it very difficult to understand. 
* There's no information about the new Design System
* The Component Library has been deprecated but that isn't reflected in the README.md
* Simplify by remove any information other than how to get the library running to the Wiki 
* Mark the Component Library as deprecated and link to its wiki page
* Add some Design System information and link to its Wiki page
> Simplify main README and include Design System

- README.md
The link to the Component Library Wiki page had changed so the link in the README was broken.
Update the link to the Wiki page
> Fix link to Component Library wiki page

- CHANGELOG.md
- assets/components/account-menu/_account-menu.scss
- design-system.md
Elements on the homepage (About) are misaligned due to the inherited `technical-documantion` wrapper.
Consolidate CSS and markup to avoid any inherited overrides.
> remove layout overrides to match GDS style

- assets/patterns/500-pages/README.md
There was an H3 introducing the first example that is not needed.
> Removed an unnecessary heading

- CHANGELOG.md
- gulpfile.js/util/pattern-library/macros/wip.html
GOV.UK elements uses a wider version which has more impact on the page. I think we should be encouraging people to use.
Changes the modifier on the class from `panel-border-narrow` to `panel-border-wide`
> Changing the inset text to match GOV.UK elements

- CHANGELOG.md
- assets/javascripts/application.js
- assets/javascripts/modules/noticeBanner.js
- assets/scss/components/_notice-banner.scss
- assets/test/specs/fixtures/notice-banner-fixture.html
- assets/test/specs/noticeBanner.spec.js
The original banner didn't have a link to close it and set a cookie to keep it closed. This led to lots of teams adding their own, which meant lots of versions of the same thing and a whole lot of different cookie names. 
This adds the missing link, which closes the banner and keeps it closed with a cookie that has _the correct name_.
> Adds a close link to the banner, with cookie

- CHANGELOG.md
- assets/javascripts/modules/reportAProblem.js
If the reportAProblem form validation passes client-side but fails on the server, the result of the ajax call is another form which replaces the existing one. The submit event handler isn't attached to the replacement form though so when it's submitted, it redirects without the CSRF token.
Call the function to attach the submit event handler after a successful ajax request in case it's a form.
> PLATY-62: Updated reportAProblem to reattach form validation after a successful submission

- CHANGELOG.md
- assets/scss/base/form/_errors.scss
The placement of the error message sits above the label pushing it down
The added css will fix the placement of the error above the checkbox and label.
> added styles to fix singleCheckbox error

- CHANGELOG.md
- assets/patterns/shutter-pages/closed-amls.html
- assets/patterns/shutter-pages/closed-tc.html
- assets/patterns/shutter-pages/notyet-tc.html
- assets/patterns/shutter-pages/permanent-tc.html
Comments were being displayed with the examples
the preceding `` had been left off some comments in pages causing the comments to be displayed alongside the examples
fix the comments
> Fixed broken comments on shutter page examples

- CHANGELOG.md
- assets/components/header/_header.scss
The logged in status message breaks the header layout.
Modify the style applied to the status message.
> Modify header styles for logged in status message

- CHANGELOG.md
- assets/components/_all-components.scss
- assets/scss/_application-base.scss
When v4 is complied the comp-lib scss files are not imported thus the header component does not have a style.
Move header style import to the components folder to isolate the logic.
> Move header sass import from shared to all components

- CHANGELOG.md
- assets/components/account-header/account-header-example.html
- assets/components/account-menu/_account-menu.scss
- assets/components/account-menu/account-menu.html
- assets/components/account-menu/account-menu.js
- assets/components/header/_header.scss
- assets/scss/base/_helpers.scss
**Resolving utility navigation styling snags.** 
The pull request resolves numerous styling issues that have been pointed out in first release for navigation bar on both mobile and desktop view. Also work has been done on the account_menu.js to correctly apply the appropriate classes to elements to show whether they are open/closed.
Fixed issue that no clicks would be registered on links on the homepage if the sub-navigation menu was open. Ticket has been deleted.
- Styling on mobile nav made to match prototype.
- Designed to match prototype. Removed 'your account' link from subnav mobile menu just show back link.
- Paddings on nav amended to match prototype.
-Transition has been added to the dropdown menu and also to the page to bring content down from behind drop down menu.
- Styles …
> MTA-2870 Resolve navigation snag list v1.0

- CHANGELOG.md
- assets/components/character-counter/README.md
- gulpfile.js/util/pattern-library/lib/parseDocumentation.js
- gulpfile.js/util/pattern-library/macros/deprecated.html
GDS have a better version of the character counter. The @hmrc/design-system-working-group decided on Friday to deprecate the HMRC version and use the GDS version.
We need to communicate this to users who are looking for a character counter in the HMRC design system.
This PR adds a deprecated banner to the top of the component in the HMRC design system and points at the GDS version.
> Deprecated character counter

- CHANGELOG.md
- gulpfile.js/tests/compileTemplate.test.js
- gulpfile.js/tests/registerHandlebarsHelpers.test.js
Editing a gulpfile test while the `watch` task was running resulted in the following errors, crashing the `watch` task
`TypeError: Attempted to wrap compile which is already wrapped`
`TypeError: Attempted to wrap registerHelper which is already wrapped`
Call `.restore()` on the spied function after use, so that it can be successfully wrapped again when the test runs again
> Prevents spies from trying to wrap functions that are already wrapped

- CHANGELOG.md
- assets/styles/alpha-and-beta-banners/README.md
- assets/styles/buttons/README.md
- assets/styles/data/README.md
- assets/styles/errors-and-validation/README.md
- assets/styles/form-elements/README.md
Not all Gov.Uk Elements style sections were linked to from the design system
Add missing folders and READMEs for each missing section
> SDT-702: Adds missing style pages that correspond to gov.uk element pages

- CHANGELOG.md
- gulpfile.js/tasks/build.js
- gulpfile.js/tasks/test.js
Running npm test on its own was failing due to missing stylesheets. Adding build as dependancy of test.
> Add build as a dependancy for test

- CHANGELOG.md
- design-system.md
There was no link to the contribution guidelines within the design system. 
This is a strategic fix to link to contribution guidelines in the github wiki, prior to including this documentation within the design system itself.
> Added in link to Contribution Guidelines on index page

- CHANGELOG.md
- gulpfile.js/tasks/changelog.js
- gulpfile.js/tests/changelog.test.js
The change log check compares `HEAD` to master and fails if they aren't the same. This is breaking builds of tags that are not the most recent commit on master.
Check instead that the commit at `HEAD` is in the remote master branch. If it is, skip the change log check as it will have already been merged.
> Check that the current commit exits in remote master

- CHANGELOG.md
- assets/scss/base/_buttons.scss
When the focus state was instantiated the background of the button (button--link) was green and should be transparent.
The background colour is wrong and confuses the user when focusing on this style of button.
Updated styles so background is transparent when focusing on button.
> Removed green background on button--link focus state

- CHANGELOG.md
- assets/components/account-menu/_account-menu.scss
When the account-menu component was introduced some styling was changed for the display of the blue border on the service-info element. This was to get the account-menu sub-menu to display properly. Unfortunately this introduced a bug that prevented the blue border-top to display on pages that didn't use the account-menu. 
Remove the blue border-top from the account-menu and revert back to it being displayed as part of the service-info element. Change the styling so the account-menu sub-nav still displays properly.
> MTA-3081: Fix issue with blue border not displaying on pages without the PTA account menu.

- CHANGELOG.md
- assets/application.js
- assets/javascripts/index.js
Stage prompt module has errors due to jQuery being loaded too late
As Stage prompt loads first it errors as it has a dependancy on jQuery. As a result of the error javascript functionality will be compromised.
For the Stage prompt module to work it depends on jQuery so I have shifted this to the top of the page as a require in the application.js. jQuery now loads first which fixes the error.
> Issue with Stageprompt not recognising JQuery

- assets/components/README.md
- assets/components/old-component-library/README.md
The reference to the old component library is in the components navigation
Remove this link and then add the contents of the page to the components landing page
> Remove the link 'Old component library' in the components navigation

- CHANGELOG.md
- assets/components/account-menu/_account-menu.scss
Using the keyboard a user is able to tab into the dropdown without it being active
Adding `display: none` to the subnav means a user will not be able to navigate inside of it until your account has been selected.
> Fixing issues where users can focus elements inside the dropdown without selecting

- CHANGELOG.md
Links to releases since 3.1.0 were broken resulting in 404s.
> Fix broken and missing release links

- CHANGELOG.md
- assets/test/config/karma.conf.js
PhantomJS has a default viewport width of 400. This means all our tests are effectively running in our mobile media-query breakpoint.
Set the default viewport size to larger than the [GOV.UK "desktop" breakpoint](https://github.com/alphagov/govuk_frontend_toolkit/blob/2011e77436fccd31f32a0a975a2bf4cc3b961495/stylesheets/_conditionals.scss#L29) of `min-width: 769px`
> Run tests in desktop viewport instead of phantom's default 400

- CHANGELOG.md
- assets/components/page-title/README.md
- assets/components/page-title/page-title-markup.html
- assets/components/page-title/page-title.html
Different services use different page titles in different formats. This is to make it consistent and accessible.
> Added page title documentation

- CHANGELOG.md
- assets/components/open-links-in-a-new-window-or-tab/README.md
The Open links in a new window or tab page contained a typo, which I've corrected.
Replaced *multiples windows* with *multiple windows*
> Corrected a Typo in the Open links in a new window or tab page

- CHANGELOG.md
- assets/styles/errors-and-validation/README.md
The link on the errors and validation page is broken
Fix link to point to correct page on Gov.uk Elements
> Fixed broken link on "errors and validation" page

- CHANGELOG.md
- assets/scss/base/form/_form.scss
In high contrast mode the input text isn't visible.
The highlighted text shows there is text in the input and it can be selected, but it's not visible.
Remove the `background-color` from inputs as per [GOV.UK Elements](https://github.com/alphagov/govuk_elements/blob/7a860c7274fd83484ba42eefe1575e72aefaf55d/assets/sass/elements/_forms.scss#L148-L149).
Thanks to @grahampaulcook for discovering this issue and its fix.
> Fix form-control in high contrast mode

- CHANGELOG.md
- assets/patterns/help-users-when-we-cannot-confirm-who-they-are/README.md
- assets/patterns/help-users-when-we-cannot-confirm-who-they-are/help-users-when-we-cannot-confirm-who-they-are-avoid.html
- assets/patterns/help-users-when-we-cannot-confirm-who-they-are/help-users-when-we-cannot-confirm-who-they-are-specific.html
- assets/patterns/help-users-when-we-cannot-confirm-who-they-are/help-users-when-we-cannot-confirm-who-they-are.html
- assets/patterns/tell-users-we-have-confirmed-who-they-are/README.md
- assets/patterns/tell-users-we-have-confirmed-who-they-are/tell-users-we-have-confirmed-who-they-are.html
Patterns for:
- how we help user when we cannot confirm who they are.
- tell users we have confirmed who they are
All services that use the identity verification microservice the first time a user signs in through Government Gateway has to have content when this fails or succeeds.
> New patterns for confirming or not confirming who someone is

- CHANGELOG.md
- gulpfile.js/tasks/version.js
- package-lock.json
- package.json
`node-git-versioning` was being pulled from github at the head of the `master` branch. It is now a scoped package so the module wasn't being found when referenced in assets-frontend.
Update the dependency in package.json to pull the scoped package from npm.
> Update node-git-versioning to scoped dependency

- CHANGELOG.md
- assets/patterns/page-not-found/page-not-found.html
- assets/patterns/service-unavailable/service-unavailable-after.html
- assets/patterns/service-unavailable/service-unavailable-replacement.html
- assets/patterns/there-is-a-problem-with-the-service/there-is-a-problem-with-the-service-link.html
- assets/patterns/there-is-a-problem-with-the-service/there-is-a-problem-with-the-service-no-contact.html
- assets/patterns/there-is-a-problem-with-the-service/there-is-a-problem-with-the-service.html
Updated examples for:
- page not found
- service unavailable
- there is a problem with the service
This included content changes and removing `<br>`s.
> Updated error page examples

- CHANGELOG.md
- assets/patterns/timeout-dialog/timeout-dialog.test.js
- assets/test/config/karma.conf.js
- gulpfile.js/config.js
Without this commit tests in the `patterns` directory aren't being run, this currently only affects `timeout-dialog.test.js`.
Add the the `patterns` directory alongside `components` in the config, fix the path in the `timeout-dialog.test.js`
To prove this works I've changed the expectation of a test and watched it fail, then corrected it and watched it pass.  This pass/fail was achieved via `npm start`
> Running the patterns tests alongside components tests.

- CHANGELOG.md
- design-system.md
Added the `mailto:` scheme to the *About* page in the design-system
> SDT-828 correct mailto link in design-system 'About' page

- CHANGELOG.md
- assets/patterns/help-users-when-we-time-them-out-of-a-service/_timeout-dialog.scss
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-not-signed-in.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-saved.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-will-not-save.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeoutDialog.js
- package-lock.json
Having 2 buttons next to each other is an anti-pattern.
Change the secondary action to a link
> Change secondary timeout button to a link

- CHANGELOG.md
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-not-signed-in.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-saved.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-will-not-save.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeoutDialog.js
The `<a>` tag was used to open the *sign-out* link, but the `</button>` tag was trying to close it.
Replace the `</button>` tag with an `</a>` tag.
> SDT-833 fix sign out link closing tag

- CHANGELOG.md
- assets/components/open-links-in-a-new-window-or-tab/README.md
Correct a couple of Typos highlighted by @russellthorn on the _Open links in a new window or tab_ page
> Corrected two typos on Open links in a new window or tab page

- CHANGELOG.md
- assets/patterns/help-users-when-we-cannot-confirm-who-they-are/help-users-when-we-cannot-confirm-who-they-are-avoid.html
- assets/patterns/service-unavailable/service-unavailable-link.html
- assets/patterns/there-is-a-problem-with-the-service/there-is-a-problem-with-the-service-link.html
Updated examples across 3 patterns that link to another service when there is an issue. The patterns are:
- help users when we cannot confirm who they are
- service unavailable
- there is a problem with the service
This is based on user research from Telford where the updated content that focused on the task was more usable than the previous content that focused on a service.
> Updated examples

- CHANGELOG.md
- assets/patterns/messages/_messages.scss
- assets/patterns/messages/messages-read.html
As the 'display: table-row' was removed from the CSS due to breaking Mark Ford's version I hadn't realised it would effect the full width behaviour. After removing the rule the table cells didn't span full width which is what we want.
Table rows in the CSS layout are not spanning full width, this relates to issue - #959 
Add `display: table-row` to the right selector
> Sdt 959 Messages pattern not spanning full width

- CHANGELOG.md
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeoutDialog.js
There was an inconsistency between the condition used for minute/minutes and second/seconds
The conditions are now equivalent.  The existing tests still pass, no change to behaviour.
> Refactor for consistency

- CHANGELOG.md
- repository.yaml
Section ids in the file referenced were causing false-positive LDS alerts
Leak Detection Service was detecting a false-positive and causing notification noise
Added exemption as the text detected was section numbers and not IP addresses
> LDS exemption

- assets/patterns/page-not-found/README.md
- assets/patterns/page-not-found/page-not-found-link.cy.html
- assets/patterns/page-not-found/page-not-found-link.html
- assets/patterns/page-not-found/page-not-found-user.cy.html
- assets/patterns/page-not-found/page-not-found-user.html
- assets/patterns/page-not-found/page-not-found.cy.html
- assets/patterns/page-not-found/page-not-found.html
This is following comments about what should and should not be classes as a page not found.
There is no evidence that we will ever know the page not found will be caused by the service or user. And the example of bookmarking a page in a journey or a confirmation would be better in those patterns because it is not a page not found.
This makes the pattern match the GOV.UK Design System but with the Welsh translations.
> Updated page not found documentation and examples

- CHANGELOG.md
- assets/error_pages/401.html
- assets/error_pages/403.html
- assets/error_pages/404.html
- assets/error_pages/500.html
This is to make the content match the HMRC Design System.
We do not have patterns for 401 and 403 pages so I have made them the same and removed any https status jargon that may confuse users.
> Updated 401, 403, 404 and 500 pages

- CHANGELOG.md
- assets/javascripts/modules/validatorFocus.js
Added backslashes to escape id's with dot notation
Using dots in id's breaks the validorFocus.js script so they need to be escaped with with two backslashes ref: https://api.jquery.com/category/selectors/
Added backslashes on the focusId via replace method
> fixed validorFocus.js to escape dots in jquery id selector

- CHANGELOG.md
- assets/components/page-heading/_page-heading.scss
Using `word-break`, `overflow-wrap` properties with the page heading stops the text from wrapping. This is due to the page heading having `display: table;` set.
Adding `table-layout: fixed` fixes this issue. Firefox also seems to need `width: 100%;`. More information can be found here - https://bugs.chromium.org/p/chromium/issues/detail?id=155767
> Added word break fix to page heading

- CHANGELOG.md
- gulpfile.js/tests/fixtures/pattern-library/design-pattern-library-template.html
- gulpfile.js/tests/renderPagesFromTemplate.test.js
The previous PR inadvertently broke a couple of tests. This was caused by the `pathPrefix` global variable not being accessed properly in the template.
This PR relies on https://github.com/hmrc/component-library-template/pull/70 being merged first.
> Fix path prefix for design system nav urls depending on environment

- assets/patterns/header/README.md
Made the use of full stops to terminate sentences consistent in the Header README.md file
> Make use of full stops consistent in Header pattern

- CHANGELOG.md
- package-lock.json
- package.json
The version of nodemon in `package.json` depends on [an affected version of flatmap-stream](https://github.com/dominictarr/event-stream/issues/116)
This is a non-issue as nodemon wasn't actually being run as part of assets-frontend. Just be sure this PR removes it.
> Remove unused nodemon dependency

- CHANGELOG.md
- assets/application.js
Use an ajaxPrefilter to block ajax requests from automatically executing inferred javascript responses where the request was across domains and made without setting an explicit dataType.
jQuery before 3.0.0 contains an potential XSS vulnerability under some specific conditions, there is a mitigation for the vulnerability detailed in this issue.
https://github.com/jquery/jquery/commit/f60729f3903d17917dc351f3ac87794de379b0cc
Added the code from a jQuery commit thread describing the potential vulnerability
> PSEC-461 Add an ajaxPrefilter to patch jQuery

- CHANGELOG.md
- assets/application.scss
- assets/styles/layout/_layout.scss
API Platform have an unusual UX use case.
End users of third party software have to complete an "authorisation journey" on MDTP to get something called an access token, which their software can then use to call our APIs. The authorisation journey includes: a start page, sign in, all the 2SV pages, all the IV pages and a "grant authority" page.
A lot of third party software is fat client, so the authorisation journey is run in a browser launched by their software - usually IE and often at a specific page width of 650px.
MDTP pages use the standard two-thirds/one-third page split at 650px, meaning a lot of word wrapping on the left and a lot of whitespace on the right. 
Add an opt-in breakpoint for services that need to be full-width at tablet viewport widths. 
* It's possible to achieve …
> Add opt-in full-width tablet breakpoint

- CHANGELOG.md
- assets/error_pages/400.html
- assets/error_pages/401.html
- assets/error_pages/403.html
- assets/error_pages/404.html
- assets/error_pages/500.html
- gulpfile.js/tasks/error-pages.js
Fixes the version number in the assets path in the static error pages, previously this relied on the environment variable TAG being set for the build through a parameter. No that we always buld on a push to master this is no longer set so the default v3-SNAPSHOT and v4-SNAPSHOT entries were being used instead.
This uses a different approach and checks for the value of the JENKINS_URL environment variable to determine if this is a release build
> SDT-1047 fix error pages assets path

- CHANGELOG.md
- assets/components/account-menu/_account-menu.scss
When navigating through the navigation bar, 'your account' doesn't highlight when the focus is on it.
Options
Because the navigation is in govuk template, in order to make this change consistent everywhere it is being used, the change needs to be made to assets frontend along with other styles of the navigation.
CSS removed that was overriding the default functionality to highlight on focus.
> DDCNLS-5647 - Your account menu wasn't highlighting on focus

- CHANGELOG.md
- assets/components/account-menu/account-menu.js
- assets/components/account-menu/account-menu.test-mobile.js
- assets/components/account-menu/account-menu.test.js
PLATUI-621: Fix issue with an aria-hidden attribute incorrectly added to account menu item.
Tested using Safari Voiceover for Mac
> PLATUI-621: Fix issue with an aria-hidden attribute incorrectly added

- CHANGELOG.md
- assets/components/account-header/account-header-example.cy.html
- assets/components/account-header/account-header-example.html
- assets/components/account-menu/_account-menu.scss
- assets/javascripts/vendor/govuk-template.js
- assets/patterns/header/header--phase-banner.html
- assets/patterns/header/header--signed-in.html
- assets/patterns/header/header.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/dialog.js
- assets/patterns/help-users-when-we-time-them-out-of-a-service/dialog.test.js
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-dialog.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-not-signed-in.cy.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-not-signed-in.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-saved.cy.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-saved.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-will-not-save.cy.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout-will-not-save.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout.cy.html
- assets/patterns/help-users-when-we-time-them-out-of-a-service/timeout.html
- template/assets/javascripts/vendor/govuk-template.js
- template/assets/stylesheets/govuk-template-ie6.css
- template/assets/stylesheets/govuk-template-ie7.css
- template/assets/stylesheets/govuk-template-ie8.css
- template/assets/stylesheets/govuk-template-print.css
- template/assets/stylesheets/govuk-template.css
This PR:
* removes the Javascript logic that conditionally shows the old cookie banner when Javascript is enabled and the user has not previously seen the cookie banner.
* removes the logic that sets the `seen_cookie_message` cookie that records whether the old cookie banner has been seen on a particular browser
Note, the styles for this banner live in https://www.github.com/hmrc/govuk-template . The removal of the govuk-template styles from assets-frontend is needed because govuk-template styles are inlined for
* the deprecated component library documentation that does not have the old cookie banner
* the deprecated design system documentation that does not have the old cookie banner
* the deprecated error pages that do not have the old cookie banner
This PR is the first of three related …
> PLATUI-1086: Delete old cookie banner

- gulpfile.js/tasks/test.js
Without this change the first build will generally fail.  This was shown by running:
```
git clone git@github.com:hmrc/assets-frontend.git && cd assets-frontend && nvm use && npm install && npm test
```
Once this has failed a re-test using:
```
npm test
```
Shows a pass.
This PR fixes that.
> Fixing sequential build steps.
